//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:35 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/&gt;
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/&gt;
 *         &lt;element name="fachdaten"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="uebermittelndeStelle" type="{http://www.xjustiz.de}Type.STRAF.BFJ.UebermittelndeStelle"/&gt;
 *                   &lt;element name="steuerungsdaten"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="nachrichtencode" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.GZR.Mitteilungen.Typ3"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="weitereAngabenBeteiligter" type="{http://www.xjustiz.de}Type.STRAF.BFJ.WeitereAngabenBeteiligter" minOccurs="0"/&gt;
 *                   &lt;element name="entscheidungsdaten"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/&gt;
 *                             &lt;element name="inhaltDerEntscheidung"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/&gt;
 *                                       &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/&gt;
 *                                       &lt;element name="ordnungswidrigkeit" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                                                 &lt;element name="rechtsvorschrift" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="verwaltungsentscheidung" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                       &lt;element name="textkennzahl" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Textkennzahl" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                       &lt;element name="statistik" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Statistik" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.straf.bfj.gzr.mitteilung.0500500")
public class NachrichtStrafBfjGzrMitteilung0500500 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten }
     *     
     */
    public NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="uebermittelndeStelle" type="{http://www.xjustiz.de}Type.STRAF.BFJ.UebermittelndeStelle"/&gt;
     *         &lt;element name="steuerungsdaten"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="nachrichtencode" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.GZR.Mitteilungen.Typ3"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="weitereAngabenBeteiligter" type="{http://www.xjustiz.de}Type.STRAF.BFJ.WeitereAngabenBeteiligter" minOccurs="0"/&gt;
     *         &lt;element name="entscheidungsdaten"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/&gt;
     *                   &lt;element name="inhaltDerEntscheidung"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/&gt;
     *                             &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/&gt;
     *                             &lt;element name="ordnungswidrigkeit" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *                                       &lt;element name="rechtsvorschrift" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="verwaltungsentscheidung" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                             &lt;element name="textkennzahl" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Textkennzahl" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                             &lt;element name="statistik" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Statistik" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uebermittelndeStelle",
        "steuerungsdaten",
        "weitereAngabenBeteiligter",
        "entscheidungsdaten"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected TypeSTRAFBFJUebermittelndeStelle uebermittelndeStelle;
        @XmlElement(required = true)
        protected NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Steuerungsdaten steuerungsdaten;
        protected TypeSTRAFBFJWeitereAngabenBeteiligter weitereAngabenBeteiligter;
        @XmlElement(required = true)
        protected NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten entscheidungsdaten;

        /**
         * Gets the value of the uebermittelndeStelle property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSTRAFBFJUebermittelndeStelle }
         *     
         */
        public TypeSTRAFBFJUebermittelndeStelle getUebermittelndeStelle() {
            return uebermittelndeStelle;
        }

        /**
         * Sets the value of the uebermittelndeStelle property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSTRAFBFJUebermittelndeStelle }
         *     
         */
        public void setUebermittelndeStelle(TypeSTRAFBFJUebermittelndeStelle value) {
            this.uebermittelndeStelle = value;
        }

        /**
         * Gets the value of the steuerungsdaten property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Steuerungsdaten }
         *     
         */
        public NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Steuerungsdaten getSteuerungsdaten() {
            return steuerungsdaten;
        }

        /**
         * Sets the value of the steuerungsdaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Steuerungsdaten }
         *     
         */
        public void setSteuerungsdaten(NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Steuerungsdaten value) {
            this.steuerungsdaten = value;
        }

        /**
         * Gets the value of the weitereAngabenBeteiligter property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSTRAFBFJWeitereAngabenBeteiligter }
         *     
         */
        public TypeSTRAFBFJWeitereAngabenBeteiligter getWeitereAngabenBeteiligter() {
            return weitereAngabenBeteiligter;
        }

        /**
         * Sets the value of the weitereAngabenBeteiligter property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSTRAFBFJWeitereAngabenBeteiligter }
         *     
         */
        public void setWeitereAngabenBeteiligter(TypeSTRAFBFJWeitereAngabenBeteiligter value) {
            this.weitereAngabenBeteiligter = value;
        }

        /**
         * Gets the value of the entscheidungsdaten property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten }
         *     
         */
        public NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten getEntscheidungsdaten() {
            return entscheidungsdaten;
        }

        /**
         * Sets the value of the entscheidungsdaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten }
         *     
         */
        public void setEntscheidungsdaten(NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten value) {
            this.entscheidungsdaten = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/&gt;
         *         &lt;element name="inhaltDerEntscheidung"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/&gt;
         *                   &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/&gt;
         *                   &lt;element name="ordnungswidrigkeit" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
         *                             &lt;element name="rechtsvorschrift" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="verwaltungsentscheidung" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift" maxOccurs="unbounded" minOccurs="0"/&gt;
         *                   &lt;element name="textkennzahl" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Textkennzahl" maxOccurs="unbounded" minOccurs="0"/&gt;
         *                   &lt;element name="statistik" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Statistik" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ordnungsdaten",
            "inhaltDerEntscheidung"
        })
        public static class Entscheidungsdaten {

            @XmlElement(required = true)
            protected TypeSTRAFBFJOrdnungsdaten ordnungsdaten;
            @XmlElement(required = true)
            protected NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung inhaltDerEntscheidung;

            /**
             * Gets the value of the ordnungsdaten property.
             * 
             * @return
             *     possible object is
             *     {@link TypeSTRAFBFJOrdnungsdaten }
             *     
             */
            public TypeSTRAFBFJOrdnungsdaten getOrdnungsdaten() {
                return ordnungsdaten;
            }

            /**
             * Sets the value of the ordnungsdaten property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeSTRAFBFJOrdnungsdaten }
             *     
             */
            public void setOrdnungsdaten(TypeSTRAFBFJOrdnungsdaten value) {
                this.ordnungsdaten = value;
            }

            /**
             * Gets the value of the inhaltDerEntscheidung property.
             * 
             * @return
             *     possible object is
             *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung }
             *     
             */
            public NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung getInhaltDerEntscheidung() {
                return inhaltDerEntscheidung;
            }

            /**
             * Sets the value of the inhaltDerEntscheidung property.
             * 
             * @param value
             *     allowed object is
             *     {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung }
             *     
             */
            public void setInhaltDerEntscheidung(NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung value) {
                this.inhaltDerEntscheidung = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/&gt;
             *         &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/&gt;
             *         &lt;element name="ordnungswidrigkeit" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
             *                   &lt;element name="rechtsvorschrift" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="verwaltungsentscheidung" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift" maxOccurs="unbounded" minOccurs="0"/&gt;
             *         &lt;element name="textkennzahl" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Textkennzahl" maxOccurs="unbounded" minOccurs="0"/&gt;
             *         &lt;element name="statistik" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Statistik" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datenRechtswirksamkeit",
                "geldbusse",
                "ordnungswidrigkeit",
                "verwaltungsentscheidung",
                "textkennzahl",
                "statistik"
            })
            public static class InhaltDerEntscheidung {

                protected TypeSTRAFBFJDatenRechtswirksamkeit datenRechtswirksamkeit;
                protected TypeSTRAFBFJBetrag geldbusse;
                protected List<NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung.Ordnungswidrigkeit> ordnungswidrigkeit;
                protected List<TypeSTRAFBFJGZRRechtsvorschrift> verwaltungsentscheidung;
                protected List<TypeSTRAFBFJGZRTextkennzahl> textkennzahl;
                protected TypeSTRAFBFJStatistik statistik;

                /**
                 * Gets the value of the datenRechtswirksamkeit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeSTRAFBFJDatenRechtswirksamkeit }
                 *     
                 */
                public TypeSTRAFBFJDatenRechtswirksamkeit getDatenRechtswirksamkeit() {
                    return datenRechtswirksamkeit;
                }

                /**
                 * Sets the value of the datenRechtswirksamkeit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeSTRAFBFJDatenRechtswirksamkeit }
                 *     
                 */
                public void setDatenRechtswirksamkeit(TypeSTRAFBFJDatenRechtswirksamkeit value) {
                    this.datenRechtswirksamkeit = value;
                }

                /**
                 * Gets the value of the geldbusse property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeSTRAFBFJBetrag }
                 *     
                 */
                public TypeSTRAFBFJBetrag getGeldbusse() {
                    return geldbusse;
                }

                /**
                 * Sets the value of the geldbusse property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeSTRAFBFJBetrag }
                 *     
                 */
                public void setGeldbusse(TypeSTRAFBFJBetrag value) {
                    this.geldbusse = value;
                }

                /**
                 * Gets the value of the ordnungswidrigkeit property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the ordnungswidrigkeit property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOrdnungswidrigkeit().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung.Ordnungswidrigkeit }
                 * 
                 * 
                 */
                public List<NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung.Ordnungswidrigkeit> getOrdnungswidrigkeit() {
                    if (ordnungswidrigkeit == null) {
                        ordnungswidrigkeit = new ArrayList<NachrichtStrafBfjGzrMitteilung0500500 .Fachdaten.Entscheidungsdaten.InhaltDerEntscheidung.Ordnungswidrigkeit>();
                    }
                    return this.ordnungswidrigkeit;
                }

                /**
                 * Gets the value of the verwaltungsentscheidung property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the verwaltungsentscheidung property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getVerwaltungsentscheidung().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TypeSTRAFBFJGZRRechtsvorschrift }
                 * 
                 * 
                 */
                public List<TypeSTRAFBFJGZRRechtsvorschrift> getVerwaltungsentscheidung() {
                    if (verwaltungsentscheidung == null) {
                        verwaltungsentscheidung = new ArrayList<TypeSTRAFBFJGZRRechtsvorschrift>();
                    }
                    return this.verwaltungsentscheidung;
                }

                /**
                 * Gets the value of the textkennzahl property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the textkennzahl property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTextkennzahl().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TypeSTRAFBFJGZRTextkennzahl }
                 * 
                 * 
                 */
                public List<TypeSTRAFBFJGZRTextkennzahl> getTextkennzahl() {
                    if (textkennzahl == null) {
                        textkennzahl = new ArrayList<TypeSTRAFBFJGZRTextkennzahl>();
                    }
                    return this.textkennzahl;
                }

                /**
                 * Gets the value of the statistik property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeSTRAFBFJStatistik }
                 *     
                 */
                public TypeSTRAFBFJStatistik getStatistik() {
                    return statistik;
                }

                /**
                 * Sets the value of the statistik property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeSTRAFBFJStatistik }
                 *     
                 */
                public void setStatistik(TypeSTRAFBFJStatistik value) {
                    this.statistik = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
                 *         &lt;element name="rechtsvorschrift" type="{http://www.xjustiz.de}Type.STRAF.BFJ.GZR.Rechtsvorschrift"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "bezeichnung",
                    "rechtsvorschrift"
                })
                public static class Ordnungswidrigkeit {

                    @XmlElement(required = true)
                    protected String bezeichnung;
                    @XmlElement(required = true)
                    protected TypeSTRAFBFJGZRRechtsvorschrift rechtsvorschrift;

                    /**
                     * Gets the value of the bezeichnung property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBezeichnung() {
                        return bezeichnung;
                    }

                    /**
                     * Sets the value of the bezeichnung property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBezeichnung(String value) {
                        this.bezeichnung = value;
                    }

                    /**
                     * Gets the value of the rechtsvorschrift property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TypeSTRAFBFJGZRRechtsvorschrift }
                     *     
                     */
                    public TypeSTRAFBFJGZRRechtsvorschrift getRechtsvorschrift() {
                        return rechtsvorschrift;
                    }

                    /**
                     * Sets the value of the rechtsvorschrift property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TypeSTRAFBFJGZRRechtsvorschrift }
                     *     
                     */
                    public void setRechtsvorschrift(TypeSTRAFBFJGZRRechtsvorschrift value) {
                        this.rechtsvorschrift = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="nachrichtencode" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.GZR.Mitteilungen.Typ3"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nachrichtencode"
        })
        public static class Steuerungsdaten {

            @XmlElement(required = true)
            protected CodeSTRAFBFJNachrichtencodeGZRMitteilungenTyp3 nachrichtencode;

            /**
             * Gets the value of the nachrichtencode property.
             * 
             * @return
             *     possible object is
             *     {@link CodeSTRAFBFJNachrichtencodeGZRMitteilungenTyp3 }
             *     
             */
            public CodeSTRAFBFJNachrichtencodeGZRMitteilungenTyp3 getNachrichtencode() {
                return nachrichtencode;
            }

            /**
             * Sets the value of the nachrichtencode property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeSTRAFBFJNachrichtencodeGZRMitteilungenTyp3 }
             *     
             */
            public void setNachrichtencode(CodeSTRAFBFJNachrichtencodeGZRMitteilungenTyp3 value) {
                this.nachrichtencode = value;
            }

        }

    }

}
