//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:44:10 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/&gt;
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/&gt;
 *         &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte" minOccurs="0"/&gt;
 *         &lt;element name="fachdaten"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="datenDerUrkunde" type="{http://www.xjustiz.de}Type.GDS.Beurkundung" maxOccurs="unbounded"/&gt;
 *                   &lt;element name="bundeslandfremdesGrundbuchblatt" type="{http://www.xjustiz.de}Type.DABAG.BundeslandfremdesGrundbuchblatt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="beschreibungDesBetroffenenRechts" type="{http://www.xjustiz.de}Type.ENOVA.BeschreibungDesBetroffenenRechts" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="artDesRechtsgeschaefts" type="{http://www.xjustiz.de}Type.ENOVA.ArtDesRechtsgeschaefts" minOccurs="0"/&gt;
 *                   &lt;element name="gegenleistung" type="{http://www.xjustiz.de}Type.ENOVA.Gegenleistung" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="erwerber_veraeusserer" type="{http://www.xjustiz.de}Type.ENOVA.Erwerber_Veraeusserer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="wertangabenNachErbSTG" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="verkehrswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="geschaeftswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="hoeheDerNotargebuehren" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="letzterEinheitswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="letzterGrundbesitzwert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="valutastandUebernommenerVerbindlichkeiten" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="jahreswertGegenleistungen" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="grundDerUebersendung" type="{http://www.xjustiz.de}Code.ENOVA.GrundDerUebersendung" minOccurs="0"/&gt;
 *                   &lt;element name="angabenZumErbfallErblasser" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="erblasser" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                             &lt;element name="gueterstand" type="{http://www.xjustiz.de}Code.ENOVA.Gueterstand" minOccurs="0"/&gt;
 *                             &lt;element name="angabenVerfuegungVonTodesWegen" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="testament.erbvertragVom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="eroeffnetAm" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="hoeheUndZusammensetzungDesNachlasses" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "schriftgutobjekte",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.enova.mitteilung.2900004")
public class NachrichtEnovaMitteilung2900004 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    protected TypeGDSSchriftgutobjekte schriftgutobjekte;
    @XmlElement(required = true)
    protected NachrichtEnovaMitteilung2900004 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the schriftgutobjekte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public TypeGDSSchriftgutobjekte getSchriftgutobjekte() {
        return schriftgutobjekte;
    }

    /**
     * Sets the value of the schriftgutobjekte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public void setSchriftgutobjekte(TypeGDSSchriftgutobjekte value) {
        this.schriftgutobjekte = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtEnovaMitteilung2900004 .Fachdaten }
     *     
     */
    public NachrichtEnovaMitteilung2900004 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtEnovaMitteilung2900004 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtEnovaMitteilung2900004 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="datenDerUrkunde" type="{http://www.xjustiz.de}Type.GDS.Beurkundung" maxOccurs="unbounded"/&gt;
     *         &lt;element name="bundeslandfremdesGrundbuchblatt" type="{http://www.xjustiz.de}Type.DABAG.BundeslandfremdesGrundbuchblatt" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="beschreibungDesBetroffenenRechts" type="{http://www.xjustiz.de}Type.ENOVA.BeschreibungDesBetroffenenRechts" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="artDesRechtsgeschaefts" type="{http://www.xjustiz.de}Type.ENOVA.ArtDesRechtsgeschaefts" minOccurs="0"/&gt;
     *         &lt;element name="gegenleistung" type="{http://www.xjustiz.de}Type.ENOVA.Gegenleistung" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="erwerber_veraeusserer" type="{http://www.xjustiz.de}Type.ENOVA.Erwerber_Veraeusserer" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="wertangabenNachErbSTG" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="verkehrswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="geschaeftswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="hoeheDerNotargebuehren" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="letzterEinheitswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="letzterGrundbesitzwert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="valutastandUebernommenerVerbindlichkeiten" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="jahreswertGegenleistungen" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="grundDerUebersendung" type="{http://www.xjustiz.de}Code.ENOVA.GrundDerUebersendung" minOccurs="0"/&gt;
     *         &lt;element name="angabenZumErbfallErblasser" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="erblasser" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *                   &lt;element name="gueterstand" type="{http://www.xjustiz.de}Code.ENOVA.Gueterstand" minOccurs="0"/&gt;
     *                   &lt;element name="angabenVerfuegungVonTodesWegen" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="testament.erbvertragVom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                             &lt;element name="eroeffnetAm" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="hoeheUndZusammensetzungDesNachlasses" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datenDerUrkunde",
        "bundeslandfremdesGrundbuchblatt",
        "beschreibungDesBetroffenenRechts",
        "artDesRechtsgeschaefts",
        "gegenleistung",
        "erwerberVeraeusserer",
        "wertangabenNachErbSTG",
        "grundDerUebersendung",
        "angabenZumErbfallErblasser",
        "hoeheUndZusammensetzungDesNachlasses"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected List<TypeGDSBeurkundung> datenDerUrkunde;
        protected List<TypeDABAGBundeslandfremdesGrundbuchblatt> bundeslandfremdesGrundbuchblatt;
        protected List<TypeENOVABeschreibungDesBetroffenenRechts> beschreibungDesBetroffenenRechts;
        protected TypeENOVAArtDesRechtsgeschaefts artDesRechtsgeschaefts;
        protected List<TypeENOVAGegenleistung> gegenleistung;
        @XmlElement(name = "erwerber_veraeusserer")
        protected List<TypeENOVAErwerberVeraeusserer> erwerberVeraeusserer;
        protected NachrichtEnovaMitteilung2900004 .Fachdaten.WertangabenNachErbSTG wertangabenNachErbSTG;
        protected CodeENOVAGrundDerUebersendung grundDerUebersendung;
        protected NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser angabenZumErbfallErblasser;
        protected String hoeheUndZusammensetzungDesNachlasses;

        /**
         * Gets the value of the datenDerUrkunde property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the datenDerUrkunde property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatenDerUrkunde().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeGDSBeurkundung }
         * 
         * 
         */
        public List<TypeGDSBeurkundung> getDatenDerUrkunde() {
            if (datenDerUrkunde == null) {
                datenDerUrkunde = new ArrayList<TypeGDSBeurkundung>();
            }
            return this.datenDerUrkunde;
        }

        /**
         * Gets the value of the bundeslandfremdesGrundbuchblatt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the bundeslandfremdesGrundbuchblatt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBundeslandfremdesGrundbuchblatt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeDABAGBundeslandfremdesGrundbuchblatt }
         * 
         * 
         */
        public List<TypeDABAGBundeslandfremdesGrundbuchblatt> getBundeslandfremdesGrundbuchblatt() {
            if (bundeslandfremdesGrundbuchblatt == null) {
                bundeslandfremdesGrundbuchblatt = new ArrayList<TypeDABAGBundeslandfremdesGrundbuchblatt>();
            }
            return this.bundeslandfremdesGrundbuchblatt;
        }

        /**
         * Gets the value of the beschreibungDesBetroffenenRechts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the beschreibungDesBetroffenenRechts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBeschreibungDesBetroffenenRechts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeENOVABeschreibungDesBetroffenenRechts }
         * 
         * 
         */
        public List<TypeENOVABeschreibungDesBetroffenenRechts> getBeschreibungDesBetroffenenRechts() {
            if (beschreibungDesBetroffenenRechts == null) {
                beschreibungDesBetroffenenRechts = new ArrayList<TypeENOVABeschreibungDesBetroffenenRechts>();
            }
            return this.beschreibungDesBetroffenenRechts;
        }

        /**
         * Gets the value of the artDesRechtsgeschaefts property.
         * 
         * @return
         *     possible object is
         *     {@link TypeENOVAArtDesRechtsgeschaefts }
         *     
         */
        public TypeENOVAArtDesRechtsgeschaefts getArtDesRechtsgeschaefts() {
            return artDesRechtsgeschaefts;
        }

        /**
         * Sets the value of the artDesRechtsgeschaefts property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeENOVAArtDesRechtsgeschaefts }
         *     
         */
        public void setArtDesRechtsgeschaefts(TypeENOVAArtDesRechtsgeschaefts value) {
            this.artDesRechtsgeschaefts = value;
        }

        /**
         * Gets the value of the gegenleistung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the gegenleistung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGegenleistung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeENOVAGegenleistung }
         * 
         * 
         */
        public List<TypeENOVAGegenleistung> getGegenleistung() {
            if (gegenleistung == null) {
                gegenleistung = new ArrayList<TypeENOVAGegenleistung>();
            }
            return this.gegenleistung;
        }

        /**
         * Gets the value of the erwerberVeraeusserer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the erwerberVeraeusserer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getErwerberVeraeusserer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeENOVAErwerberVeraeusserer }
         * 
         * 
         */
        public List<TypeENOVAErwerberVeraeusserer> getErwerberVeraeusserer() {
            if (erwerberVeraeusserer == null) {
                erwerberVeraeusserer = new ArrayList<TypeENOVAErwerberVeraeusserer>();
            }
            return this.erwerberVeraeusserer;
        }

        /**
         * Gets the value of the wertangabenNachErbSTG property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtEnovaMitteilung2900004 .Fachdaten.WertangabenNachErbSTG }
         *     
         */
        public NachrichtEnovaMitteilung2900004 .Fachdaten.WertangabenNachErbSTG getWertangabenNachErbSTG() {
            return wertangabenNachErbSTG;
        }

        /**
         * Sets the value of the wertangabenNachErbSTG property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtEnovaMitteilung2900004 .Fachdaten.WertangabenNachErbSTG }
         *     
         */
        public void setWertangabenNachErbSTG(NachrichtEnovaMitteilung2900004 .Fachdaten.WertangabenNachErbSTG value) {
            this.wertangabenNachErbSTG = value;
        }

        /**
         * Gets the value of the grundDerUebersendung property.
         * 
         * @return
         *     possible object is
         *     {@link CodeENOVAGrundDerUebersendung }
         *     
         */
        public CodeENOVAGrundDerUebersendung getGrundDerUebersendung() {
            return grundDerUebersendung;
        }

        /**
         * Sets the value of the grundDerUebersendung property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeENOVAGrundDerUebersendung }
         *     
         */
        public void setGrundDerUebersendung(CodeENOVAGrundDerUebersendung value) {
            this.grundDerUebersendung = value;
        }

        /**
         * Gets the value of the angabenZumErbfallErblasser property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser }
         *     
         */
        public NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser getAngabenZumErbfallErblasser() {
            return angabenZumErbfallErblasser;
        }

        /**
         * Sets the value of the angabenZumErbfallErblasser property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser }
         *     
         */
        public void setAngabenZumErbfallErblasser(NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser value) {
            this.angabenZumErbfallErblasser = value;
        }

        /**
         * Gets the value of the hoeheUndZusammensetzungDesNachlasses property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoeheUndZusammensetzungDesNachlasses() {
            return hoeheUndZusammensetzungDesNachlasses;
        }

        /**
         * Sets the value of the hoeheUndZusammensetzungDesNachlasses property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoeheUndZusammensetzungDesNachlasses(String value) {
            this.hoeheUndZusammensetzungDesNachlasses = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="erblasser" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
         *         &lt;element name="gueterstand" type="{http://www.xjustiz.de}Code.ENOVA.Gueterstand" minOccurs="0"/&gt;
         *         &lt;element name="angabenVerfuegungVonTodesWegen" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="testament.erbvertragVom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                   &lt;element name="eroeffnetAm" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "erblasser",
            "gueterstand",
            "angabenVerfuegungVonTodesWegen"
        })
        public static class AngabenZumErbfallErblasser {

            @XmlElement(required = true)
            protected TypeGDSRefRollennummer erblasser;
            protected CodeENOVAGueterstand gueterstand;
            protected List<NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser.AngabenVerfuegungVonTodesWegen> angabenVerfuegungVonTodesWegen;

            /**
             * Gets the value of the erblasser property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSRefRollennummer }
             *     
             */
            public TypeGDSRefRollennummer getErblasser() {
                return erblasser;
            }

            /**
             * Sets the value of the erblasser property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSRefRollennummer }
             *     
             */
            public void setErblasser(TypeGDSRefRollennummer value) {
                this.erblasser = value;
            }

            /**
             * Gets the value of the gueterstand property.
             * 
             * @return
             *     possible object is
             *     {@link CodeENOVAGueterstand }
             *     
             */
            public CodeENOVAGueterstand getGueterstand() {
                return gueterstand;
            }

            /**
             * Sets the value of the gueterstand property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeENOVAGueterstand }
             *     
             */
            public void setGueterstand(CodeENOVAGueterstand value) {
                this.gueterstand = value;
            }

            /**
             * Gets the value of the angabenVerfuegungVonTodesWegen property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the angabenVerfuegungVonTodesWegen property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAngabenVerfuegungVonTodesWegen().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser.AngabenVerfuegungVonTodesWegen }
             * 
             * 
             */
            public List<NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser.AngabenVerfuegungVonTodesWegen> getAngabenVerfuegungVonTodesWegen() {
                if (angabenVerfuegungVonTodesWegen == null) {
                    angabenVerfuegungVonTodesWegen = new ArrayList<NachrichtEnovaMitteilung2900004 .Fachdaten.AngabenZumErbfallErblasser.AngabenVerfuegungVonTodesWegen>();
                }
                return this.angabenVerfuegungVonTodesWegen;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="testament.erbvertragVom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="eroeffnetAm" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "testamentErbvertragVom",
                "eroeffnetAm"
            })
            public static class AngabenVerfuegungVonTodesWegen {

                @XmlElement(name = "testament.erbvertragVom", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar testamentErbvertragVom;
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar eroeffnetAm;

                /**
                 * Gets the value of the testamentErbvertragVom property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getTestamentErbvertragVom() {
                    return testamentErbvertragVom;
                }

                /**
                 * Sets the value of the testamentErbvertragVom property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setTestamentErbvertragVom(XMLGregorianCalendar value) {
                    this.testamentErbvertragVom = value;
                }

                /**
                 * Gets the value of the eroeffnetAm property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getEroeffnetAm() {
                    return eroeffnetAm;
                }

                /**
                 * Sets the value of the eroeffnetAm property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setEroeffnetAm(XMLGregorianCalendar value) {
                    this.eroeffnetAm = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="verkehrswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="geschaeftswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="hoeheDerNotargebuehren" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="letzterEinheitswert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="letzterGrundbesitzwert" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="valutastandUebernommenerVerbindlichkeiten" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="jahreswertGegenleistungen" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "verkehrswert",
            "geschaeftswert",
            "hoeheDerNotargebuehren",
            "letzterEinheitswert",
            "letzterGrundbesitzwert",
            "valutastandUebernommenerVerbindlichkeiten",
            "jahreswertGegenleistungen"
        })
        public static class WertangabenNachErbSTG {

            protected TypeGDSGeldbetrag verkehrswert;
            protected TypeGDSGeldbetrag geschaeftswert;
            protected TypeGDSGeldbetrag hoeheDerNotargebuehren;
            protected TypeGDSGeldbetrag letzterEinheitswert;
            protected TypeGDSGeldbetrag letzterGrundbesitzwert;
            protected TypeGDSGeldbetrag valutastandUebernommenerVerbindlichkeiten;
            protected TypeGDSGeldbetrag jahreswertGegenleistungen;

            /**
             * Gets the value of the verkehrswert property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getVerkehrswert() {
                return verkehrswert;
            }

            /**
             * Sets the value of the verkehrswert property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setVerkehrswert(TypeGDSGeldbetrag value) {
                this.verkehrswert = value;
            }

            /**
             * Gets the value of the geschaeftswert property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getGeschaeftswert() {
                return geschaeftswert;
            }

            /**
             * Sets the value of the geschaeftswert property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setGeschaeftswert(TypeGDSGeldbetrag value) {
                this.geschaeftswert = value;
            }

            /**
             * Gets the value of the hoeheDerNotargebuehren property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getHoeheDerNotargebuehren() {
                return hoeheDerNotargebuehren;
            }

            /**
             * Sets the value of the hoeheDerNotargebuehren property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setHoeheDerNotargebuehren(TypeGDSGeldbetrag value) {
                this.hoeheDerNotargebuehren = value;
            }

            /**
             * Gets the value of the letzterEinheitswert property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getLetzterEinheitswert() {
                return letzterEinheitswert;
            }

            /**
             * Sets the value of the letzterEinheitswert property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setLetzterEinheitswert(TypeGDSGeldbetrag value) {
                this.letzterEinheitswert = value;
            }

            /**
             * Gets the value of the letzterGrundbesitzwert property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getLetzterGrundbesitzwert() {
                return letzterGrundbesitzwert;
            }

            /**
             * Sets the value of the letzterGrundbesitzwert property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setLetzterGrundbesitzwert(TypeGDSGeldbetrag value) {
                this.letzterGrundbesitzwert = value;
            }

            /**
             * Gets the value of the valutastandUebernommenerVerbindlichkeiten property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getValutastandUebernommenerVerbindlichkeiten() {
                return valutastandUebernommenerVerbindlichkeiten;
            }

            /**
             * Sets the value of the valutastandUebernommenerVerbindlichkeiten property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setValutastandUebernommenerVerbindlichkeiten(TypeGDSGeldbetrag value) {
                this.valutastandUebernommenerVerbindlichkeiten = value;
            }

            /**
             * Gets the value of the jahreswertGegenleistungen property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getJahreswertGegenleistungen() {
                return jahreswertGegenleistungen;
            }

            /**
             * Sets the value of the jahreswertGegenleistungen property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setJahreswertGegenleistungen(TypeGDSGeldbetrag value) {
                this.jahreswertGegenleistungen = value;
            }

        }

    }

}
