//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:45 PM CEST 
//


package com.java.xsd.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.AUSS.FachlicheDaten complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.AUSS.FachlicheDaten"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="verfahrensdauer" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="ansprechpartnerAnbietendeStelle" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/&gt;
 *         &lt;element name="ansprechpartnerArchiv" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/&gt;
 *         &lt;element name="aktenzeichenArchiv" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
 *         &lt;element name="eingangsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="anhaengigSeit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="erledigungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *         &lt;element name="erledigungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="weglegungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="aufbewahrungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="auswahl_fachgebiet"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="register"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="referenz.organisation" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                             &lt;element name="eintragungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="gruendungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="geschaeftszweck" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="kapital" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
 *                             &lt;element name="loeschungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="nachfolgefirmen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="zivil"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ve.verfahrensart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="gesamtstreitgegenstand" type="{http://www.xjustiz.de}Type.GDS.Verfahrensgegenstand" minOccurs="0"/&gt;
 *                             &lt;element name="uebernahmeVonGericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
 *                             &lt;element name="uebernahmeVonAktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
 *                             &lt;element name="vorVerfahrenBesonderheit" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="vorVerfahrenGericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
 *                             &lt;element name="vorVerfahrenAktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
 *                             &lt;element name="jurisKennzeichen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="ve.sachgebiet" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="ve.erledigungsGrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="ve.vorherigesVerfahren" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="ve.weglegungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="ve.anbietungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="streitgegenstand" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="art" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                                       &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                                       &lt;element name="streitgegenstandsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                                       &lt;element name="zeitraum" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fach"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="herkunftUnterlagen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="bemerkungen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="verfahrensart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="azHoechsteInstanz" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
 *                             &lt;element name="gerichtHoechsteInstanz" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
 *                             &lt;element name="rechtsmittelArt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="entscheidungsdokumentationGericht" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                             &lt;element name="aktenzeichenVorinstanzen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                             &lt;element name="beteiligungOeffentlicherDienst" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="eingereichtVon" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.AUSS.FachlicheDaten", propOrder = {
    "verfahrensdauer",
    "ansprechpartnerAnbietendeStelle",
    "ansprechpartnerArchiv",
    "aktenzeichenArchiv",
    "eingangsdatum",
    "anhaengigSeit",
    "erledigungsgrund",
    "erledigungsdatum",
    "weglegungsdatum",
    "aufbewahrungsdatum",
    "auswahlFachgebiet"
})
public class TypeAUSSFachlicheDaten {

    protected BigInteger verfahrensdauer;
    protected String ansprechpartnerAnbietendeStelle;
    protected String ansprechpartnerArchiv;
    protected TypeGDSAktenzeichen aktenzeichenArchiv;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar eingangsdatum;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar anhaengigSeit;
    protected String erledigungsgrund;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar erledigungsdatum;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar weglegungsdatum;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar aufbewahrungsdatum;
    @XmlElement(name = "auswahl_fachgebiet", required = true)
    protected TypeAUSSFachlicheDaten.AuswahlFachgebiet auswahlFachgebiet;

    /**
     * Gets the value of the verfahrensdauer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVerfahrensdauer() {
        return verfahrensdauer;
    }

    /**
     * Sets the value of the verfahrensdauer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVerfahrensdauer(BigInteger value) {
        this.verfahrensdauer = value;
    }

    /**
     * Gets the value of the ansprechpartnerAnbietendeStelle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsprechpartnerAnbietendeStelle() {
        return ansprechpartnerAnbietendeStelle;
    }

    /**
     * Sets the value of the ansprechpartnerAnbietendeStelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsprechpartnerAnbietendeStelle(String value) {
        this.ansprechpartnerAnbietendeStelle = value;
    }

    /**
     * Gets the value of the ansprechpartnerArchiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsprechpartnerArchiv() {
        return ansprechpartnerArchiv;
    }

    /**
     * Sets the value of the ansprechpartnerArchiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsprechpartnerArchiv(String value) {
        this.ansprechpartnerArchiv = value;
    }

    /**
     * Gets the value of the aktenzeichenArchiv property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public TypeGDSAktenzeichen getAktenzeichenArchiv() {
        return aktenzeichenArchiv;
    }

    /**
     * Sets the value of the aktenzeichenArchiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public void setAktenzeichenArchiv(TypeGDSAktenzeichen value) {
        this.aktenzeichenArchiv = value;
    }

    /**
     * Gets the value of the eingangsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEingangsdatum() {
        return eingangsdatum;
    }

    /**
     * Sets the value of the eingangsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEingangsdatum(XMLGregorianCalendar value) {
        this.eingangsdatum = value;
    }

    /**
     * Gets the value of the anhaengigSeit property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAnhaengigSeit() {
        return anhaengigSeit;
    }

    /**
     * Sets the value of the anhaengigSeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAnhaengigSeit(XMLGregorianCalendar value) {
        this.anhaengigSeit = value;
    }

    /**
     * Gets the value of the erledigungsgrund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErledigungsgrund() {
        return erledigungsgrund;
    }

    /**
     * Sets the value of the erledigungsgrund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErledigungsgrund(String value) {
        this.erledigungsgrund = value;
    }

    /**
     * Gets the value of the erledigungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getErledigungsdatum() {
        return erledigungsdatum;
    }

    /**
     * Sets the value of the erledigungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setErledigungsdatum(XMLGregorianCalendar value) {
        this.erledigungsdatum = value;
    }

    /**
     * Gets the value of the weglegungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWeglegungsdatum() {
        return weglegungsdatum;
    }

    /**
     * Sets the value of the weglegungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWeglegungsdatum(XMLGregorianCalendar value) {
        this.weglegungsdatum = value;
    }

    /**
     * Gets the value of the aufbewahrungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAufbewahrungsdatum() {
        return aufbewahrungsdatum;
    }

    /**
     * Sets the value of the aufbewahrungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAufbewahrungsdatum(XMLGregorianCalendar value) {
        this.aufbewahrungsdatum = value;
    }

    /**
     * Gets the value of the auswahlFachgebiet property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet }
     *     
     */
    public TypeAUSSFachlicheDaten.AuswahlFachgebiet getAuswahlFachgebiet() {
        return auswahlFachgebiet;
    }

    /**
     * Sets the value of the auswahlFachgebiet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet }
     *     
     */
    public void setAuswahlFachgebiet(TypeAUSSFachlicheDaten.AuswahlFachgebiet value) {
        this.auswahlFachgebiet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="register"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="referenz.organisation" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *                   &lt;element name="eintragungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="gruendungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="geschaeftszweck" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="kapital" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
     *                   &lt;element name="loeschungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="nachfolgefirmen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="zivil"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ve.verfahrensart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="gesamtstreitgegenstand" type="{http://www.xjustiz.de}Type.GDS.Verfahrensgegenstand" minOccurs="0"/&gt;
     *                   &lt;element name="uebernahmeVonGericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
     *                   &lt;element name="uebernahmeVonAktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
     *                   &lt;element name="vorVerfahrenBesonderheit" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="vorVerfahrenGericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
     *                   &lt;element name="vorVerfahrenAktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
     *                   &lt;element name="jurisKennzeichen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="ve.sachgebiet" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="ve.erledigungsGrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="ve.vorherigesVerfahren" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="ve.weglegungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="ve.anbietungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="streitgegenstand" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="art" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                             &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                             &lt;element name="streitgegenstandsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                             &lt;element name="zeitraum" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fach"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="herkunftUnterlagen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="bemerkungen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="verfahrensart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="azHoechsteInstanz" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
     *                   &lt;element name="gerichtHoechsteInstanz" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
     *                   &lt;element name="rechtsmittelArt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="entscheidungsdokumentationGericht" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                   &lt;element name="aktenzeichenVorinstanzen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                   &lt;element name="beteiligungOeffentlicherDienst" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="eingereichtVon" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "register",
        "zivil",
        "fach"
    })
    public static class AuswahlFachgebiet {

        protected TypeAUSSFachlicheDaten.AuswahlFachgebiet.Register register;
        protected TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil zivil;
        protected TypeAUSSFachlicheDaten.AuswahlFachgebiet.Fach fach;

        /**
         * Gets the value of the register property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Register }
         *     
         */
        public TypeAUSSFachlicheDaten.AuswahlFachgebiet.Register getRegister() {
            return register;
        }

        /**
         * Sets the value of the register property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Register }
         *     
         */
        public void setRegister(TypeAUSSFachlicheDaten.AuswahlFachgebiet.Register value) {
            this.register = value;
        }

        /**
         * Gets the value of the zivil property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil }
         *     
         */
        public TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil getZivil() {
            return zivil;
        }

        /**
         * Sets the value of the zivil property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil }
         *     
         */
        public void setZivil(TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil value) {
            this.zivil = value;
        }

        /**
         * Gets the value of the fach property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Fach }
         *     
         */
        public TypeAUSSFachlicheDaten.AuswahlFachgebiet.Fach getFach() {
            return fach;
        }

        /**
         * Sets the value of the fach property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Fach }
         *     
         */
        public void setFach(TypeAUSSFachlicheDaten.AuswahlFachgebiet.Fach value) {
            this.fach = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="herkunftUnterlagen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="bemerkungen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="verfahrensart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="azHoechsteInstanz" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
         *         &lt;element name="gerichtHoechsteInstanz" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
         *         &lt;element name="rechtsmittelArt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="entscheidungsdokumentationGericht" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="aktenzeichenVorinstanzen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" maxOccurs="unbounded" minOccurs="0"/&gt;
         *         &lt;element name="beteiligungOeffentlicherDienst" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="eingereichtVon" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "herkunftUnterlagen",
            "bemerkungen",
            "verfahrensart",
            "azHoechsteInstanz",
            "gerichtHoechsteInstanz",
            "rechtsmittelArt",
            "entscheidungsdokumentationGericht",
            "aktenzeichenVorinstanzen",
            "beteiligungOeffentlicherDienst",
            "eingereichtVon"
        })
        public static class Fach {

            protected String herkunftUnterlagen;
            protected String bemerkungen;
            protected String verfahrensart;
            protected TypeGDSAktenzeichen azHoechsteInstanz;
            protected CodeGDSGerichteTyp3 gerichtHoechsteInstanz;
            protected String rechtsmittelArt;
            protected String entscheidungsdokumentationGericht;
            protected List<TypeGDSAktenzeichen> aktenzeichenVorinstanzen;
            @XmlElement(defaultValue = "false")
            protected Boolean beteiligungOeffentlicherDienst;
            protected String eingereichtVon;

            /**
             * Gets the value of the herkunftUnterlagen property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHerkunftUnterlagen() {
                return herkunftUnterlagen;
            }

            /**
             * Sets the value of the herkunftUnterlagen property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHerkunftUnterlagen(String value) {
                this.herkunftUnterlagen = value;
            }

            /**
             * Gets the value of the bemerkungen property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBemerkungen() {
                return bemerkungen;
            }

            /**
             * Sets the value of the bemerkungen property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBemerkungen(String value) {
                this.bemerkungen = value;
            }

            /**
             * Gets the value of the verfahrensart property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVerfahrensart() {
                return verfahrensart;
            }

            /**
             * Sets the value of the verfahrensart property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVerfahrensart(String value) {
                this.verfahrensart = value;
            }

            /**
             * Gets the value of the azHoechsteInstanz property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSAktenzeichen }
             *     
             */
            public TypeGDSAktenzeichen getAzHoechsteInstanz() {
                return azHoechsteInstanz;
            }

            /**
             * Sets the value of the azHoechsteInstanz property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSAktenzeichen }
             *     
             */
            public void setAzHoechsteInstanz(TypeGDSAktenzeichen value) {
                this.azHoechsteInstanz = value;
            }

            /**
             * Gets the value of the gerichtHoechsteInstanz property.
             * 
             * @return
             *     possible object is
             *     {@link CodeGDSGerichteTyp3 }
             *     
             */
            public CodeGDSGerichteTyp3 getGerichtHoechsteInstanz() {
                return gerichtHoechsteInstanz;
            }

            /**
             * Sets the value of the gerichtHoechsteInstanz property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeGDSGerichteTyp3 }
             *     
             */
            public void setGerichtHoechsteInstanz(CodeGDSGerichteTyp3 value) {
                this.gerichtHoechsteInstanz = value;
            }

            /**
             * Gets the value of the rechtsmittelArt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRechtsmittelArt() {
                return rechtsmittelArt;
            }

            /**
             * Sets the value of the rechtsmittelArt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRechtsmittelArt(String value) {
                this.rechtsmittelArt = value;
            }

            /**
             * Gets the value of the entscheidungsdokumentationGericht property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntscheidungsdokumentationGericht() {
                return entscheidungsdokumentationGericht;
            }

            /**
             * Sets the value of the entscheidungsdokumentationGericht property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntscheidungsdokumentationGericht(String value) {
                this.entscheidungsdokumentationGericht = value;
            }

            /**
             * Gets the value of the aktenzeichenVorinstanzen property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the aktenzeichenVorinstanzen property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAktenzeichenVorinstanzen().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TypeGDSAktenzeichen }
             * 
             * 
             */
            public List<TypeGDSAktenzeichen> getAktenzeichenVorinstanzen() {
                if (aktenzeichenVorinstanzen == null) {
                    aktenzeichenVorinstanzen = new ArrayList<TypeGDSAktenzeichen>();
                }
                return this.aktenzeichenVorinstanzen;
            }

            /**
             * Gets the value of the beteiligungOeffentlicherDienst property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isBeteiligungOeffentlicherDienst() {
                return beteiligungOeffentlicherDienst;
            }

            /**
             * Sets the value of the beteiligungOeffentlicherDienst property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setBeteiligungOeffentlicherDienst(Boolean value) {
                this.beteiligungOeffentlicherDienst = value;
            }

            /**
             * Gets the value of the eingereichtVon property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEingereichtVon() {
                return eingereichtVon;
            }

            /**
             * Sets the value of the eingereichtVon property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEingereichtVon(String value) {
                this.eingereichtVon = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="referenz.organisation" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
         *         &lt;element name="eintragungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="gruendungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="geschaeftszweck" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="kapital" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/&gt;
         *         &lt;element name="loeschungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="nachfolgefirmen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "referenzOrganisation",
            "eintragungsdatum",
            "gruendungsdatum",
            "geschaeftszweck",
            "kapital",
            "loeschungsdatum",
            "nachfolgefirmen"
        })
        public static class Register {

            @XmlElement(name = "referenz.organisation", required = true)
            protected TypeGDSRefRollennummer referenzOrganisation;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar eintragungsdatum;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar gruendungsdatum;
            protected String geschaeftszweck;
            protected TypeGDSGeldbetrag kapital;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar loeschungsdatum;
            protected String nachfolgefirmen;

            /**
             * Gets the value of the referenzOrganisation property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSRefRollennummer }
             *     
             */
            public TypeGDSRefRollennummer getReferenzOrganisation() {
                return referenzOrganisation;
            }

            /**
             * Sets the value of the referenzOrganisation property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSRefRollennummer }
             *     
             */
            public void setReferenzOrganisation(TypeGDSRefRollennummer value) {
                this.referenzOrganisation = value;
            }

            /**
             * Gets the value of the eintragungsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEintragungsdatum() {
                return eintragungsdatum;
            }

            /**
             * Sets the value of the eintragungsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEintragungsdatum(XMLGregorianCalendar value) {
                this.eintragungsdatum = value;
            }

            /**
             * Gets the value of the gruendungsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGruendungsdatum() {
                return gruendungsdatum;
            }

            /**
             * Sets the value of the gruendungsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGruendungsdatum(XMLGregorianCalendar value) {
                this.gruendungsdatum = value;
            }

            /**
             * Gets the value of the geschaeftszweck property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGeschaeftszweck() {
                return geschaeftszweck;
            }

            /**
             * Sets the value of the geschaeftszweck property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGeschaeftszweck(String value) {
                this.geschaeftszweck = value;
            }

            /**
             * Gets the value of the kapital property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public TypeGDSGeldbetrag getKapital() {
                return kapital;
            }

            /**
             * Sets the value of the kapital property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSGeldbetrag }
             *     
             */
            public void setKapital(TypeGDSGeldbetrag value) {
                this.kapital = value;
            }

            /**
             * Gets the value of the loeschungsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getLoeschungsdatum() {
                return loeschungsdatum;
            }

            /**
             * Sets the value of the loeschungsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setLoeschungsdatum(XMLGregorianCalendar value) {
                this.loeschungsdatum = value;
            }

            /**
             * Gets the value of the nachfolgefirmen property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNachfolgefirmen() {
                return nachfolgefirmen;
            }

            /**
             * Sets the value of the nachfolgefirmen property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNachfolgefirmen(String value) {
                this.nachfolgefirmen = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ve.verfahrensart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="gesamtstreitgegenstand" type="{http://www.xjustiz.de}Type.GDS.Verfahrensgegenstand" minOccurs="0"/&gt;
         *         &lt;element name="uebernahmeVonGericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
         *         &lt;element name="uebernahmeVonAktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
         *         &lt;element name="vorVerfahrenBesonderheit" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="vorVerfahrenGericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
         *         &lt;element name="vorVerfahrenAktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/&gt;
         *         &lt;element name="jurisKennzeichen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="ve.sachgebiet" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="ve.erledigungsGrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="ve.vorherigesVerfahren" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="ve.weglegungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="ve.anbietungsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *         &lt;element name="streitgegenstand" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="art" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *                   &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *                   &lt;element name="streitgegenstandsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *                   &lt;element name="zeitraum" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "veVerfahrensart",
            "gesamtstreitgegenstand",
            "uebernahmeVonGericht",
            "uebernahmeVonAktenzeichen",
            "vorVerfahrenBesonderheit",
            "vorVerfahrenGericht",
            "vorVerfahrenAktenzeichen",
            "jurisKennzeichen",
            "veSachgebiet",
            "veErledigungsGrund",
            "veVorherigesVerfahren",
            "veWeglegungsgrund",
            "veAnbietungsgrund",
            "streitgegenstand"
        })
        public static class Zivil {

            @XmlElement(name = "ve.verfahrensart")
            protected String veVerfahrensart;
            protected TypeGDSVerfahrensgegenstand gesamtstreitgegenstand;
            protected CodeGDSGerichteTyp3 uebernahmeVonGericht;
            protected TypeGDSAktenzeichen uebernahmeVonAktenzeichen;
            protected String vorVerfahrenBesonderheit;
            protected CodeGDSGerichteTyp3 vorVerfahrenGericht;
            protected TypeGDSAktenzeichen vorVerfahrenAktenzeichen;
            @XmlElement(defaultValue = "false")
            protected boolean jurisKennzeichen;
            @XmlElement(name = "ve.sachgebiet")
            protected String veSachgebiet;
            @XmlElement(name = "ve.erledigungsGrund")
            protected String veErledigungsGrund;
            @XmlElement(name = "ve.vorherigesVerfahren")
            protected String veVorherigesVerfahren;
            @XmlElement(name = "ve.weglegungsgrund")
            protected String veWeglegungsgrund;
            @XmlElement(name = "ve.anbietungsgrund")
            protected String veAnbietungsgrund;
            protected List<TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil.Streitgegenstand> streitgegenstand;

            /**
             * Gets the value of the veVerfahrensart property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVeVerfahrensart() {
                return veVerfahrensart;
            }

            /**
             * Sets the value of the veVerfahrensart property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVeVerfahrensart(String value) {
                this.veVerfahrensart = value;
            }

            /**
             * Gets the value of the gesamtstreitgegenstand property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSVerfahrensgegenstand }
             *     
             */
            public TypeGDSVerfahrensgegenstand getGesamtstreitgegenstand() {
                return gesamtstreitgegenstand;
            }

            /**
             * Sets the value of the gesamtstreitgegenstand property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSVerfahrensgegenstand }
             *     
             */
            public void setGesamtstreitgegenstand(TypeGDSVerfahrensgegenstand value) {
                this.gesamtstreitgegenstand = value;
            }

            /**
             * Gets the value of the uebernahmeVonGericht property.
             * 
             * @return
             *     possible object is
             *     {@link CodeGDSGerichteTyp3 }
             *     
             */
            public CodeGDSGerichteTyp3 getUebernahmeVonGericht() {
                return uebernahmeVonGericht;
            }

            /**
             * Sets the value of the uebernahmeVonGericht property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeGDSGerichteTyp3 }
             *     
             */
            public void setUebernahmeVonGericht(CodeGDSGerichteTyp3 value) {
                this.uebernahmeVonGericht = value;
            }

            /**
             * Gets the value of the uebernahmeVonAktenzeichen property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSAktenzeichen }
             *     
             */
            public TypeGDSAktenzeichen getUebernahmeVonAktenzeichen() {
                return uebernahmeVonAktenzeichen;
            }

            /**
             * Sets the value of the uebernahmeVonAktenzeichen property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSAktenzeichen }
             *     
             */
            public void setUebernahmeVonAktenzeichen(TypeGDSAktenzeichen value) {
                this.uebernahmeVonAktenzeichen = value;
            }

            /**
             * Gets the value of the vorVerfahrenBesonderheit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVorVerfahrenBesonderheit() {
                return vorVerfahrenBesonderheit;
            }

            /**
             * Sets the value of the vorVerfahrenBesonderheit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVorVerfahrenBesonderheit(String value) {
                this.vorVerfahrenBesonderheit = value;
            }

            /**
             * Gets the value of the vorVerfahrenGericht property.
             * 
             * @return
             *     possible object is
             *     {@link CodeGDSGerichteTyp3 }
             *     
             */
            public CodeGDSGerichteTyp3 getVorVerfahrenGericht() {
                return vorVerfahrenGericht;
            }

            /**
             * Sets the value of the vorVerfahrenGericht property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeGDSGerichteTyp3 }
             *     
             */
            public void setVorVerfahrenGericht(CodeGDSGerichteTyp3 value) {
                this.vorVerfahrenGericht = value;
            }

            /**
             * Gets the value of the vorVerfahrenAktenzeichen property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSAktenzeichen }
             *     
             */
            public TypeGDSAktenzeichen getVorVerfahrenAktenzeichen() {
                return vorVerfahrenAktenzeichen;
            }

            /**
             * Sets the value of the vorVerfahrenAktenzeichen property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSAktenzeichen }
             *     
             */
            public void setVorVerfahrenAktenzeichen(TypeGDSAktenzeichen value) {
                this.vorVerfahrenAktenzeichen = value;
            }

            /**
             * Gets the value of the jurisKennzeichen property.
             * 
             */
            public boolean isJurisKennzeichen() {
                return jurisKennzeichen;
            }

            /**
             * Sets the value of the jurisKennzeichen property.
             * 
             */
            public void setJurisKennzeichen(boolean value) {
                this.jurisKennzeichen = value;
            }

            /**
             * Gets the value of the veSachgebiet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVeSachgebiet() {
                return veSachgebiet;
            }

            /**
             * Sets the value of the veSachgebiet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVeSachgebiet(String value) {
                this.veSachgebiet = value;
            }

            /**
             * Gets the value of the veErledigungsGrund property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVeErledigungsGrund() {
                return veErledigungsGrund;
            }

            /**
             * Sets the value of the veErledigungsGrund property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVeErledigungsGrund(String value) {
                this.veErledigungsGrund = value;
            }

            /**
             * Gets the value of the veVorherigesVerfahren property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVeVorherigesVerfahren() {
                return veVorherigesVerfahren;
            }

            /**
             * Sets the value of the veVorherigesVerfahren property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVeVorherigesVerfahren(String value) {
                this.veVorherigesVerfahren = value;
            }

            /**
             * Gets the value of the veWeglegungsgrund property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVeWeglegungsgrund() {
                return veWeglegungsgrund;
            }

            /**
             * Sets the value of the veWeglegungsgrund property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVeWeglegungsgrund(String value) {
                this.veWeglegungsgrund = value;
            }

            /**
             * Gets the value of the veAnbietungsgrund property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVeAnbietungsgrund() {
                return veAnbietungsgrund;
            }

            /**
             * Sets the value of the veAnbietungsgrund property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVeAnbietungsgrund(String value) {
                this.veAnbietungsgrund = value;
            }

            /**
             * Gets the value of the streitgegenstand property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the streitgegenstand property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStreitgegenstand().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil.Streitgegenstand }
             * 
             * 
             */
            public List<TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil.Streitgegenstand> getStreitgegenstand() {
                if (streitgegenstand == null) {
                    streitgegenstand = new ArrayList<TypeAUSSFachlicheDaten.AuswahlFachgebiet.Zivil.Streitgegenstand>();
                }
                return this.streitgegenstand;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="art" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
             *         &lt;element name="bezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
             *         &lt;element name="streitgegenstandsgrund" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
             *         &lt;element name="zeitraum" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "art",
                "bezeichnung",
                "streitgegenstandsgrund",
                "zeitraum"
            })
            public static class Streitgegenstand {

                protected String art;
                protected String bezeichnung;
                protected String streitgegenstandsgrund;
                protected TypeGDSXdomeaZeitraumType zeitraum;

                /**
                 * Gets the value of the art property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArt() {
                    return art;
                }

                /**
                 * Sets the value of the art property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArt(String value) {
                    this.art = value;
                }

                /**
                 * Gets the value of the bezeichnung property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBezeichnung() {
                    return bezeichnung;
                }

                /**
                 * Sets the value of the bezeichnung property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBezeichnung(String value) {
                    this.bezeichnung = value;
                }

                /**
                 * Gets the value of the streitgegenstandsgrund property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStreitgegenstandsgrund() {
                    return streitgegenstandsgrund;
                }

                /**
                 * Sets the value of the streitgegenstandsgrund property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStreitgegenstandsgrund(String value) {
                    this.streitgegenstandsgrund = value;
                }

                /**
                 * Gets the value of the zeitraum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeGDSXdomeaZeitraumType }
                 *     
                 */
                public TypeGDSXdomeaZeitraumType getZeitraum() {
                    return zeitraum;
                }

                /**
                 * Sets the value of the zeitraum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeGDSXdomeaZeitraumType }
                 *     
                 */
                public void setZeitraum(TypeGDSXdomeaZeitraumType value) {
                    this.zeitraum = value;
                }

            }

        }

    }

}
