//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:28 PM CEST 
//


package com.java.xsd.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.VAG.GerichtlicheEntscheidung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.VAG.GerichtlicheEntscheidung"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="entscheidung.ID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *         &lt;element name="entscheidung.ID.erstinstanz" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *         &lt;element name="auskunft.ID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *         &lt;element name="entscheidungsdatum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="datum.antrag.abaenderung" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="datum.antrag.isolierteErstentscheidung" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="datum.wiederaufnahme" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="datum.urspruenglicheEntscheidung" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="datum.parteienvereinbarung" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="gericht.urspruenglicheEntscheidung" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3" minOccurs="0"/&gt;
 *         &lt;element name="aktenzeichen.urspruenglicheEntscheidung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *         &lt;element name="entscheidung.ID.urspruenglicheEntscheidung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *         &lt;element name="familie" type="{http://www.xjustiz.de}Type.VAG.Familie"/&gt;
 *         &lt;element name="versicherter" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *         &lt;element name="andererEhegatte" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *         &lt;element name="referenz.entscheidung" type="{http://www.xjustiz.de}Type.GDS.Ref.SGO" minOccurs="0"/&gt;
 *         &lt;element name="istTeilentscheidung" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ausgleich" type="{http://www.xjustiz.de}Code.VAG.Ausgleich"/&gt;
 *         &lt;element name="zumAnrecht" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="anrecht.ID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                   &lt;element name="ordnungskriterium" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                   &lt;element name="ausgleichswert" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="bezugsgroesse" type="{http://www.xjustiz.de}Code.VAG.Bezugsgroesse"/&gt;
 *                   &lt;element name="andereBezugsgroesse" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="mindestkapitalbetrag" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="teilungsart" type="{http://www.xjustiz.de}Code.VAG.Teilungsart.Entscheidung"/&gt;
 *                   &lt;element name="verzinsung" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="auswahl_zinssatz"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice&gt;
 *                                       &lt;element name="zinssatzInProzent" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
 *                                       &lt;element name="prozentUeberBasiszinssatz" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
 *                                     &lt;/choice&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="kapitalbetrag" type="{http://www.xjustiz.de}Type.VAG.Decimal.9_2" minOccurs="0"/&gt;
 *                             &lt;element name="auswahl_zinsbeginn"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice&gt;
 *                                       &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="sonstigerZeitpunkt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                                     &lt;/choice&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="auswahl_zinsende"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice&gt;
 *                                       &lt;element name="zinsende.rechtskraft" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                                       &lt;element name="bisZum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                     &lt;/choice&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="tarif" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="ausgleichspflichtiger" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                   &lt;element name="ausgleichsberechtigter" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                   &lt;element name="zielversorgungstraeger.ausgleichsberechtigter" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" minOccurs="0"/&gt;
 *                   &lt;element name="versorgungstraeger.ausgleichpflichtiger" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" minOccurs="0"/&gt;
 *                   &lt;element name="internationaleWertpapierkennnummer" type="{http://www.xjustiz.de}Type.VAG.ISIN" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.VAG.GerichtlicheEntscheidung", propOrder = {
    "entscheidungID",
    "entscheidungIDErstinstanz",
    "auskunftID",
    "entscheidungsdatum",
    "datumAntragAbaenderung",
    "datumAntragIsolierteErstentscheidung",
    "datumWiederaufnahme",
    "datumUrspruenglicheEntscheidung",
    "datumParteienvereinbarung",
    "gerichtUrspruenglicheEntscheidung",
    "aktenzeichenUrspruenglicheEntscheidung",
    "entscheidungIDUrspruenglicheEntscheidung",
    "familie",
    "versicherter",
    "andererEhegatte",
    "referenzEntscheidung",
    "istTeilentscheidung",
    "ausgleich",
    "zumAnrecht"
})
public class TypeVAGGerichtlicheEntscheidung {

    @XmlElement(name = "entscheidung.ID", required = true)
    protected String entscheidungID;
    @XmlElement(name = "entscheidung.ID.erstinstanz")
    protected String entscheidungIDErstinstanz;
    @XmlElement(name = "auskunft.ID", required = true)
    protected String auskunftID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar entscheidungsdatum;
    @XmlElement(name = "datum.antrag.abaenderung")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumAntragAbaenderung;
    @XmlElement(name = "datum.antrag.isolierteErstentscheidung")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumAntragIsolierteErstentscheidung;
    @XmlElement(name = "datum.wiederaufnahme")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumWiederaufnahme;
    @XmlElement(name = "datum.urspruenglicheEntscheidung")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumUrspruenglicheEntscheidung;
    @XmlElement(name = "datum.parteienvereinbarung")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumParteienvereinbarung;
    @XmlElement(name = "gericht.urspruenglicheEntscheidung")
    protected CodeGDSGerichteTyp3 gerichtUrspruenglicheEntscheidung;
    @XmlElement(name = "aktenzeichen.urspruenglicheEntscheidung")
    protected String aktenzeichenUrspruenglicheEntscheidung;
    @XmlElement(name = "entscheidung.ID.urspruenglicheEntscheidung")
    protected String entscheidungIDUrspruenglicheEntscheidung;
    @XmlElement(required = true)
    protected TypeVAGFamilie familie;
    @XmlElement(required = true)
    protected TypeGDSRefRollennummer versicherter;
    @XmlElement(required = true)
    protected TypeGDSRefRollennummer andererEhegatte;
    @XmlElement(name = "referenz.entscheidung")
    protected TypeGDSRefSGO referenzEntscheidung;
    protected boolean istTeilentscheidung;
    @XmlElement(required = true)
    protected CodeVAGAusgleich ausgleich;
    protected List<TypeVAGGerichtlicheEntscheidung.ZumAnrecht> zumAnrecht;

    /**
     * Gets the value of the entscheidungID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntscheidungID() {
        return entscheidungID;
    }

    /**
     * Sets the value of the entscheidungID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntscheidungID(String value) {
        this.entscheidungID = value;
    }

    /**
     * Gets the value of the entscheidungIDErstinstanz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntscheidungIDErstinstanz() {
        return entscheidungIDErstinstanz;
    }

    /**
     * Sets the value of the entscheidungIDErstinstanz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntscheidungIDErstinstanz(String value) {
        this.entscheidungIDErstinstanz = value;
    }

    /**
     * Gets the value of the auskunftID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuskunftID() {
        return auskunftID;
    }

    /**
     * Sets the value of the auskunftID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuskunftID(String value) {
        this.auskunftID = value;
    }

    /**
     * Gets the value of the entscheidungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntscheidungsdatum() {
        return entscheidungsdatum;
    }

    /**
     * Sets the value of the entscheidungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntscheidungsdatum(XMLGregorianCalendar value) {
        this.entscheidungsdatum = value;
    }

    /**
     * Gets the value of the datumAntragAbaenderung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumAntragAbaenderung() {
        return datumAntragAbaenderung;
    }

    /**
     * Sets the value of the datumAntragAbaenderung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumAntragAbaenderung(XMLGregorianCalendar value) {
        this.datumAntragAbaenderung = value;
    }

    /**
     * Gets the value of the datumAntragIsolierteErstentscheidung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumAntragIsolierteErstentscheidung() {
        return datumAntragIsolierteErstentscheidung;
    }

    /**
     * Sets the value of the datumAntragIsolierteErstentscheidung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumAntragIsolierteErstentscheidung(XMLGregorianCalendar value) {
        this.datumAntragIsolierteErstentscheidung = value;
    }

    /**
     * Gets the value of the datumWiederaufnahme property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumWiederaufnahme() {
        return datumWiederaufnahme;
    }

    /**
     * Sets the value of the datumWiederaufnahme property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumWiederaufnahme(XMLGregorianCalendar value) {
        this.datumWiederaufnahme = value;
    }

    /**
     * Gets the value of the datumUrspruenglicheEntscheidung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumUrspruenglicheEntscheidung() {
        return datumUrspruenglicheEntscheidung;
    }

    /**
     * Sets the value of the datumUrspruenglicheEntscheidung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumUrspruenglicheEntscheidung(XMLGregorianCalendar value) {
        this.datumUrspruenglicheEntscheidung = value;
    }

    /**
     * Gets the value of the datumParteienvereinbarung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumParteienvereinbarung() {
        return datumParteienvereinbarung;
    }

    /**
     * Sets the value of the datumParteienvereinbarung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumParteienvereinbarung(XMLGregorianCalendar value) {
        this.datumParteienvereinbarung = value;
    }

    /**
     * Gets the value of the gerichtUrspruenglicheEntscheidung property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGDSGerichteTyp3 }
     *     
     */
    public CodeGDSGerichteTyp3 getGerichtUrspruenglicheEntscheidung() {
        return gerichtUrspruenglicheEntscheidung;
    }

    /**
     * Sets the value of the gerichtUrspruenglicheEntscheidung property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGDSGerichteTyp3 }
     *     
     */
    public void setGerichtUrspruenglicheEntscheidung(CodeGDSGerichteTyp3 value) {
        this.gerichtUrspruenglicheEntscheidung = value;
    }

    /**
     * Gets the value of the aktenzeichenUrspruenglicheEntscheidung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAktenzeichenUrspruenglicheEntscheidung() {
        return aktenzeichenUrspruenglicheEntscheidung;
    }

    /**
     * Sets the value of the aktenzeichenUrspruenglicheEntscheidung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAktenzeichenUrspruenglicheEntscheidung(String value) {
        this.aktenzeichenUrspruenglicheEntscheidung = value;
    }

    /**
     * Gets the value of the entscheidungIDUrspruenglicheEntscheidung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntscheidungIDUrspruenglicheEntscheidung() {
        return entscheidungIDUrspruenglicheEntscheidung;
    }

    /**
     * Sets the value of the entscheidungIDUrspruenglicheEntscheidung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntscheidungIDUrspruenglicheEntscheidung(String value) {
        this.entscheidungIDUrspruenglicheEntscheidung = value;
    }

    /**
     * Gets the value of the familie property.
     * 
     * @return
     *     possible object is
     *     {@link TypeVAGFamilie }
     *     
     */
    public TypeVAGFamilie getFamilie() {
        return familie;
    }

    /**
     * Sets the value of the familie property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeVAGFamilie }
     *     
     */
    public void setFamilie(TypeVAGFamilie value) {
        this.familie = value;
    }

    /**
     * Gets the value of the versicherter property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public TypeGDSRefRollennummer getVersicherter() {
        return versicherter;
    }

    /**
     * Sets the value of the versicherter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public void setVersicherter(TypeGDSRefRollennummer value) {
        this.versicherter = value;
    }

    /**
     * Gets the value of the andererEhegatte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public TypeGDSRefRollennummer getAndererEhegatte() {
        return andererEhegatte;
    }

    /**
     * Sets the value of the andererEhegatte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public void setAndererEhegatte(TypeGDSRefRollennummer value) {
        this.andererEhegatte = value;
    }

    /**
     * Gets the value of the referenzEntscheidung property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefSGO }
     *     
     */
    public TypeGDSRefSGO getReferenzEntscheidung() {
        return referenzEntscheidung;
    }

    /**
     * Sets the value of the referenzEntscheidung property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefSGO }
     *     
     */
    public void setReferenzEntscheidung(TypeGDSRefSGO value) {
        this.referenzEntscheidung = value;
    }

    /**
     * Gets the value of the istTeilentscheidung property.
     * 
     */
    public boolean isIstTeilentscheidung() {
        return istTeilentscheidung;
    }

    /**
     * Sets the value of the istTeilentscheidung property.
     * 
     */
    public void setIstTeilentscheidung(boolean value) {
        this.istTeilentscheidung = value;
    }

    /**
     * Gets the value of the ausgleich property.
     * 
     * @return
     *     possible object is
     *     {@link CodeVAGAusgleich }
     *     
     */
    public CodeVAGAusgleich getAusgleich() {
        return ausgleich;
    }

    /**
     * Sets the value of the ausgleich property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeVAGAusgleich }
     *     
     */
    public void setAusgleich(CodeVAGAusgleich value) {
        this.ausgleich = value;
    }

    /**
     * Gets the value of the zumAnrecht property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the zumAnrecht property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZumAnrecht().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht }
     * 
     * 
     */
    public List<TypeVAGGerichtlicheEntscheidung.ZumAnrecht> getZumAnrecht() {
        if (zumAnrecht == null) {
            zumAnrecht = new ArrayList<TypeVAGGerichtlicheEntscheidung.ZumAnrecht>();
        }
        return this.zumAnrecht;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="anrecht.ID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *         &lt;element name="ordnungskriterium" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *         &lt;element name="ausgleichswert" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="bezugsgroesse" type="{http://www.xjustiz.de}Code.VAG.Bezugsgroesse"/&gt;
     *         &lt;element name="andereBezugsgroesse" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="mindestkapitalbetrag" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="teilungsart" type="{http://www.xjustiz.de}Code.VAG.Teilungsart.Entscheidung"/&gt;
     *         &lt;element name="verzinsung" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="auswahl_zinssatz"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;choice&gt;
     *                             &lt;element name="zinssatzInProzent" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
     *                             &lt;element name="prozentUeberBasiszinssatz" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
     *                           &lt;/choice&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="kapitalbetrag" type="{http://www.xjustiz.de}Type.VAG.Decimal.9_2" minOccurs="0"/&gt;
     *                   &lt;element name="auswahl_zinsbeginn"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;choice&gt;
     *                             &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                             &lt;element name="sonstigerZeitpunkt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *                           &lt;/choice&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="auswahl_zinsende"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;choice&gt;
     *                             &lt;element name="zinsende.rechtskraft" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                             &lt;element name="bisZum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                           &lt;/choice&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="tarif" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="ausgleichspflichtiger" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *         &lt;element name="ausgleichsberechtigter" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *         &lt;element name="zielversorgungstraeger.ausgleichsberechtigter" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" minOccurs="0"/&gt;
     *         &lt;element name="versorgungstraeger.ausgleichpflichtiger" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" minOccurs="0"/&gt;
     *         &lt;element name="internationaleWertpapierkennnummer" type="{http://www.xjustiz.de}Type.VAG.ISIN" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "anrechtID",
        "ordnungskriterium",
        "ausgleichswert",
        "bezugsgroesse",
        "andereBezugsgroesse",
        "mindestkapitalbetrag",
        "teilungsart",
        "verzinsung",
        "tarif",
        "ausgleichspflichtiger",
        "ausgleichsberechtigter",
        "zielversorgungstraegerAusgleichsberechtigter",
        "versorgungstraegerAusgleichpflichtiger",
        "internationaleWertpapierkennnummer"
    })
    public static class ZumAnrecht {

        @XmlElement(name = "anrecht.ID", required = true)
        protected String anrechtID;
        @XmlElement(required = true)
        protected String ordnungskriterium;
        @XmlElement(required = true)
        protected BigDecimal ausgleichswert;
        @XmlElement(required = true)
        protected CodeVAGBezugsgroesse bezugsgroesse;
        protected String andereBezugsgroesse;
        protected BigDecimal mindestkapitalbetrag;
        @XmlElement(required = true)
        protected CodeVAGTeilungsartEntscheidung teilungsart;
        protected List<TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung> verzinsung;
        protected String tarif;
        @XmlElement(required = true)
        protected TypeGDSRefRollennummer ausgleichspflichtiger;
        @XmlElement(required = true)
        protected TypeGDSRefRollennummer ausgleichsberechtigter;
        @XmlElement(name = "zielversorgungstraeger.ausgleichsberechtigter")
        protected TypeGDSRefRollennummer zielversorgungstraegerAusgleichsberechtigter;
        @XmlElement(name = "versorgungstraeger.ausgleichpflichtiger")
        protected TypeGDSRefRollennummer versorgungstraegerAusgleichpflichtiger;
        protected String internationaleWertpapierkennnummer;

        /**
         * Gets the value of the anrechtID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnrechtID() {
            return anrechtID;
        }

        /**
         * Sets the value of the anrechtID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnrechtID(String value) {
            this.anrechtID = value;
        }

        /**
         * Gets the value of the ordnungskriterium property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrdnungskriterium() {
            return ordnungskriterium;
        }

        /**
         * Sets the value of the ordnungskriterium property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrdnungskriterium(String value) {
            this.ordnungskriterium = value;
        }

        /**
         * Gets the value of the ausgleichswert property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAusgleichswert() {
            return ausgleichswert;
        }

        /**
         * Sets the value of the ausgleichswert property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAusgleichswert(BigDecimal value) {
            this.ausgleichswert = value;
        }

        /**
         * Gets the value of the bezugsgroesse property.
         * 
         * @return
         *     possible object is
         *     {@link CodeVAGBezugsgroesse }
         *     
         */
        public CodeVAGBezugsgroesse getBezugsgroesse() {
            return bezugsgroesse;
        }

        /**
         * Sets the value of the bezugsgroesse property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeVAGBezugsgroesse }
         *     
         */
        public void setBezugsgroesse(CodeVAGBezugsgroesse value) {
            this.bezugsgroesse = value;
        }

        /**
         * Gets the value of the andereBezugsgroesse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAndereBezugsgroesse() {
            return andereBezugsgroesse;
        }

        /**
         * Sets the value of the andereBezugsgroesse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAndereBezugsgroesse(String value) {
            this.andereBezugsgroesse = value;
        }

        /**
         * Gets the value of the mindestkapitalbetrag property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMindestkapitalbetrag() {
            return mindestkapitalbetrag;
        }

        /**
         * Sets the value of the mindestkapitalbetrag property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMindestkapitalbetrag(BigDecimal value) {
            this.mindestkapitalbetrag = value;
        }

        /**
         * Gets the value of the teilungsart property.
         * 
         * @return
         *     possible object is
         *     {@link CodeVAGTeilungsartEntscheidung }
         *     
         */
        public CodeVAGTeilungsartEntscheidung getTeilungsart() {
            return teilungsart;
        }

        /**
         * Sets the value of the teilungsart property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeVAGTeilungsartEntscheidung }
         *     
         */
        public void setTeilungsart(CodeVAGTeilungsartEntscheidung value) {
            this.teilungsart = value;
        }

        /**
         * Gets the value of the verzinsung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the verzinsung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVerzinsung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung }
         * 
         * 
         */
        public List<TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung> getVerzinsung() {
            if (verzinsung == null) {
                verzinsung = new ArrayList<TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung>();
            }
            return this.verzinsung;
        }

        /**
         * Gets the value of the tarif property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarif() {
            return tarif;
        }

        /**
         * Sets the value of the tarif property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarif(String value) {
            this.tarif = value;
        }

        /**
         * Gets the value of the ausgleichspflichtiger property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getAusgleichspflichtiger() {
            return ausgleichspflichtiger;
        }

        /**
         * Sets the value of the ausgleichspflichtiger property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setAusgleichspflichtiger(TypeGDSRefRollennummer value) {
            this.ausgleichspflichtiger = value;
        }

        /**
         * Gets the value of the ausgleichsberechtigter property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getAusgleichsberechtigter() {
            return ausgleichsberechtigter;
        }

        /**
         * Sets the value of the ausgleichsberechtigter property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setAusgleichsberechtigter(TypeGDSRefRollennummer value) {
            this.ausgleichsberechtigter = value;
        }

        /**
         * Gets the value of the zielversorgungstraegerAusgleichsberechtigter property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getZielversorgungstraegerAusgleichsberechtigter() {
            return zielversorgungstraegerAusgleichsberechtigter;
        }

        /**
         * Sets the value of the zielversorgungstraegerAusgleichsberechtigter property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setZielversorgungstraegerAusgleichsberechtigter(TypeGDSRefRollennummer value) {
            this.zielversorgungstraegerAusgleichsberechtigter = value;
        }

        /**
         * Gets the value of the versorgungstraegerAusgleichpflichtiger property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getVersorgungstraegerAusgleichpflichtiger() {
            return versorgungstraegerAusgleichpflichtiger;
        }

        /**
         * Sets the value of the versorgungstraegerAusgleichpflichtiger property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setVersorgungstraegerAusgleichpflichtiger(TypeGDSRefRollennummer value) {
            this.versorgungstraegerAusgleichpflichtiger = value;
        }

        /**
         * Gets the value of the internationaleWertpapierkennnummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternationaleWertpapierkennnummer() {
            return internationaleWertpapierkennnummer;
        }

        /**
         * Sets the value of the internationaleWertpapierkennnummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternationaleWertpapierkennnummer(String value) {
            this.internationaleWertpapierkennnummer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="auswahl_zinssatz"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;choice&gt;
         *                   &lt;element name="zinssatzInProzent" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
         *                   &lt;element name="prozentUeberBasiszinssatz" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
         *                 &lt;/choice&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="kapitalbetrag" type="{http://www.xjustiz.de}Type.VAG.Decimal.9_2" minOccurs="0"/&gt;
         *         &lt;element name="auswahl_zinsbeginn"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;choice&gt;
         *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                   &lt;element name="sonstigerZeitpunkt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
         *                 &lt;/choice&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="auswahl_zinsende"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;choice&gt;
         *                   &lt;element name="zinsende.rechtskraft" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *                   &lt;element name="bisZum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                 &lt;/choice&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "auswahlZinssatz",
            "kapitalbetrag",
            "auswahlZinsbeginn",
            "auswahlZinsende"
        })
        public static class Verzinsung {

            @XmlElement(name = "auswahl_zinssatz", required = true)
            protected TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinssatz auswahlZinssatz;
            protected BigDecimal kapitalbetrag;
            @XmlElement(name = "auswahl_zinsbeginn", required = true)
            protected TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsbeginn auswahlZinsbeginn;
            @XmlElement(name = "auswahl_zinsende", required = true)
            protected TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsende auswahlZinsende;

            /**
             * Gets the value of the auswahlZinssatz property.
             * 
             * @return
             *     possible object is
             *     {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinssatz }
             *     
             */
            public TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinssatz getAuswahlZinssatz() {
                return auswahlZinssatz;
            }

            /**
             * Sets the value of the auswahlZinssatz property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinssatz }
             *     
             */
            public void setAuswahlZinssatz(TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinssatz value) {
                this.auswahlZinssatz = value;
            }

            /**
             * Gets the value of the kapitalbetrag property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getKapitalbetrag() {
                return kapitalbetrag;
            }

            /**
             * Sets the value of the kapitalbetrag property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setKapitalbetrag(BigDecimal value) {
                this.kapitalbetrag = value;
            }

            /**
             * Gets the value of the auswahlZinsbeginn property.
             * 
             * @return
             *     possible object is
             *     {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsbeginn }
             *     
             */
            public TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsbeginn getAuswahlZinsbeginn() {
                return auswahlZinsbeginn;
            }

            /**
             * Sets the value of the auswahlZinsbeginn property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsbeginn }
             *     
             */
            public void setAuswahlZinsbeginn(TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsbeginn value) {
                this.auswahlZinsbeginn = value;
            }

            /**
             * Gets the value of the auswahlZinsende property.
             * 
             * @return
             *     possible object is
             *     {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsende }
             *     
             */
            public TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsende getAuswahlZinsende() {
                return auswahlZinsende;
            }

            /**
             * Sets the value of the auswahlZinsende property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsende }
             *     
             */
            public void setAuswahlZinsende(TypeVAGGerichtlicheEntscheidung.ZumAnrecht.Verzinsung.AuswahlZinsende value) {
                this.auswahlZinsende = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="sonstigerZeitpunkt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
             *       &lt;/choice&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datum",
                "sonstigerZeitpunkt"
            })
            public static class AuswahlZinsbeginn {

                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar datum;
                protected String sonstigerZeitpunkt;

                /**
                 * Gets the value of the datum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDatum() {
                    return datum;
                }

                /**
                 * Sets the value of the datum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDatum(XMLGregorianCalendar value) {
                    this.datum = value;
                }

                /**
                 * Gets the value of the sonstigerZeitpunkt property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSonstigerZeitpunkt() {
                    return sonstigerZeitpunkt;
                }

                /**
                 * Sets the value of the sonstigerZeitpunkt property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSonstigerZeitpunkt(String value) {
                    this.sonstigerZeitpunkt = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="zinsende.rechtskraft" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
             *         &lt;element name="bisZum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *       &lt;/choice&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "zinsendeRechtskraft",
                "bisZum"
            })
            public static class AuswahlZinsende {

                @XmlElement(name = "zinsende.rechtskraft")
                protected Boolean zinsendeRechtskraft;
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar bisZum;

                /**
                 * Gets the value of the zinsendeRechtskraft property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isZinsendeRechtskraft() {
                    return zinsendeRechtskraft;
                }

                /**
                 * Sets the value of the zinsendeRechtskraft property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setZinsendeRechtskraft(Boolean value) {
                    this.zinsendeRechtskraft = value;
                }

                /**
                 * Gets the value of the bisZum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getBisZum() {
                    return bisZum;
                }

                /**
                 * Sets the value of the bisZum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setBisZum(XMLGregorianCalendar value) {
                    this.bisZum = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="zinssatzInProzent" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
             *         &lt;element name="prozentUeberBasiszinssatz" type="{http://www.xjustiz.de}Type.VAG.Decimal.4_2"/&gt;
             *       &lt;/choice&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "zinssatzInProzent",
                "prozentUeberBasiszinssatz"
            })
            public static class AuswahlZinssatz {

                protected BigDecimal zinssatzInProzent;
                protected BigDecimal prozentUeberBasiszinssatz;

                /**
                 * Gets the value of the zinssatzInProzent property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getZinssatzInProzent() {
                    return zinssatzInProzent;
                }

                /**
                 * Sets the value of the zinssatzInProzent property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setZinssatzInProzent(BigDecimal value) {
                    this.zinssatzInProzent = value;
                }

                /**
                 * Gets the value of the prozentUeberBasiszinssatz property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getProzentUeberBasiszinssatz() {
                    return prozentUeberBasiszinssatz;
                }

                /**
                 * Sets the value of the prozentUeberBasiszinssatz property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setProzentUeberBasiszinssatz(BigDecimal value) {
                    this.prozentUeberBasiszinssatz = value;
                }

            }

        }

    }

}
