//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:35 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.STRAF.Beschlagnahme complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.STRAF.Beschlagnahme"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="fuehrerschein" type="{http://www.xjustiz.de}Type.STRAF.Fuehrerschein" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="gegenstand" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="art" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                   &lt;element name="erlaeuterung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="betroffener" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                   &lt;element name="herkunftsbezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
 *                   &lt;element name="typ" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
 *                   &lt;element name="kennzeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="nationalitaetskennzeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="FIN" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="gegenstandsnummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="motornummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="hinweise" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="besondereMerkmale" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="farbe" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="materialbezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="erlMaterialbezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.STRAF.Beschlagnahme", propOrder = {
    "person",
    "datum",
    "fuehrerschein",
    "gegenstand"
})
public class TypeSTRAFBeschlagnahme {

    @XmlElement(required = true)
    protected TypeGDSRefRollennummer person;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    protected List<TypeSTRAFFuehrerschein> fuehrerschein;
    protected List<TypeSTRAFBeschlagnahme.Gegenstand> gegenstand;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public TypeGDSRefRollennummer getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public void setPerson(TypeGDSRefRollennummer value) {
        this.person = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the fuehrerschein property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the fuehrerschein property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFuehrerschein().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeSTRAFFuehrerschein }
     * 
     * 
     */
    public List<TypeSTRAFFuehrerschein> getFuehrerschein() {
        if (fuehrerschein == null) {
            fuehrerschein = new ArrayList<TypeSTRAFFuehrerschein>();
        }
        return this.fuehrerschein;
    }

    /**
     * Gets the value of the gegenstand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the gegenstand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGegenstand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeSTRAFBeschlagnahme.Gegenstand }
     * 
     * 
     */
    public List<TypeSTRAFBeschlagnahme.Gegenstand> getGegenstand() {
        if (gegenstand == null) {
            gegenstand = new ArrayList<TypeSTRAFBeschlagnahme.Gegenstand>();
        }
        return this.gegenstand;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="art" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *         &lt;element name="erlaeuterung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="betroffener" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *         &lt;element name="herkunftsbezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
     *         &lt;element name="typ" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/&gt;
     *         &lt;element name="kennzeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="nationalitaetskennzeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="FIN" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="gegenstandsnummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="motornummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="hinweise" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="besondereMerkmale" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="farbe" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="materialbezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="erlMaterialbezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "art",
        "erlaeuterung",
        "betroffener",
        "herkunftsbezeichnung",
        "typ",
        "kennzeichen",
        "nationalitaetskennzeichen",
        "fin",
        "gegenstandsnummer",
        "motornummer",
        "hinweise",
        "besondereMerkmale",
        "farbe",
        "materialbezeichnung",
        "erlMaterialbezeichnung"
    })
    public static class Gegenstand {

        @XmlElement(required = true)
        protected String art;
        protected String erlaeuterung;
        @XmlElement(required = true)
        protected TypeGDSRefRollennummer betroffener;
        protected String herkunftsbezeichnung;
        protected String typ;
        protected String kennzeichen;
        protected String nationalitaetskennzeichen;
        @XmlElement(name = "FIN")
        protected String fin;
        protected String gegenstandsnummer;
        protected String motornummer;
        protected String hinweise;
        protected String besondereMerkmale;
        protected String farbe;
        protected String materialbezeichnung;
        protected String erlMaterialbezeichnung;

        /**
         * Gets the value of the art property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArt() {
            return art;
        }

        /**
         * Sets the value of the art property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArt(String value) {
            this.art = value;
        }

        /**
         * Gets the value of the erlaeuterung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErlaeuterung() {
            return erlaeuterung;
        }

        /**
         * Sets the value of the erlaeuterung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErlaeuterung(String value) {
            this.erlaeuterung = value;
        }

        /**
         * Gets the value of the betroffener property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getBetroffener() {
            return betroffener;
        }

        /**
         * Sets the value of the betroffener property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setBetroffener(TypeGDSRefRollennummer value) {
            this.betroffener = value;
        }

        /**
         * Gets the value of the herkunftsbezeichnung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHerkunftsbezeichnung() {
            return herkunftsbezeichnung;
        }

        /**
         * Sets the value of the herkunftsbezeichnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHerkunftsbezeichnung(String value) {
            this.herkunftsbezeichnung = value;
        }

        /**
         * Gets the value of the typ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTyp() {
            return typ;
        }

        /**
         * Sets the value of the typ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTyp(String value) {
            this.typ = value;
        }

        /**
         * Gets the value of the kennzeichen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKennzeichen() {
            return kennzeichen;
        }

        /**
         * Sets the value of the kennzeichen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKennzeichen(String value) {
            this.kennzeichen = value;
        }

        /**
         * Gets the value of the nationalitaetskennzeichen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNationalitaetskennzeichen() {
            return nationalitaetskennzeichen;
        }

        /**
         * Sets the value of the nationalitaetskennzeichen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNationalitaetskennzeichen(String value) {
            this.nationalitaetskennzeichen = value;
        }

        /**
         * Gets the value of the fin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFIN() {
            return fin;
        }

        /**
         * Sets the value of the fin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFIN(String value) {
            this.fin = value;
        }

        /**
         * Gets the value of the gegenstandsnummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGegenstandsnummer() {
            return gegenstandsnummer;
        }

        /**
         * Sets the value of the gegenstandsnummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGegenstandsnummer(String value) {
            this.gegenstandsnummer = value;
        }

        /**
         * Gets the value of the motornummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMotornummer() {
            return motornummer;
        }

        /**
         * Sets the value of the motornummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMotornummer(String value) {
            this.motornummer = value;
        }

        /**
         * Gets the value of the hinweise property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHinweise() {
            return hinweise;
        }

        /**
         * Sets the value of the hinweise property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHinweise(String value) {
            this.hinweise = value;
        }

        /**
         * Gets the value of the besondereMerkmale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBesondereMerkmale() {
            return besondereMerkmale;
        }

        /**
         * Sets the value of the besondereMerkmale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBesondereMerkmale(String value) {
            this.besondereMerkmale = value;
        }

        /**
         * Gets the value of the farbe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFarbe() {
            return farbe;
        }

        /**
         * Sets the value of the farbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFarbe(String value) {
            this.farbe = value;
        }

        /**
         * Gets the value of the materialbezeichnung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterialbezeichnung() {
            return materialbezeichnung;
        }

        /**
         * Sets the value of the materialbezeichnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterialbezeichnung(String value) {
            this.materialbezeichnung = value;
        }

        /**
         * Gets the value of the erlMaterialbezeichnung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErlMaterialbezeichnung() {
            return erlMaterialbezeichnung;
        }

        /**
         * Sets the value of the erlMaterialbezeichnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErlMaterialbezeichnung(String value) {
            this.erlMaterialbezeichnung = value;
        }

    }

}
