//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:44:17 PM CEST 
//


package com.java.xsd.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Hier können detaillierte Angaben (z.B. Name, Anschrift) zum Beteiligten eines Verfahrens nebst zugehöriger Rolle (z.B. Beklagter, Beschwerdeführer, Ehefrau, Rechtsanwalt, Zeuge) oder mehrerer Rollen (z.B. Kläger und Berufungsbeklagter) im Verfahren übergeben werden.
 * 
 * <p>Java class for Type.GDS.Beteiligung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.GDS.Beteiligung"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rolle" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="rollennummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="rollenID" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="id" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                             &lt;element name="ref.instanznummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="rollenbezeichnung" type="{http://www.xjustiz.de}Code.GDS.Rollenbezeichnung" minOccurs="0"/&gt;
 *                   &lt;element name="nr" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="geschaeftszeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                   &lt;element name="referenz" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="naehereBezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="beteiligter" type="{http://www.xjustiz.de}Type.GDS.Beteiligter"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.GDS.Beteiligung", propOrder = {
    "rolle",
    "beteiligter"
})
public class TypeGDSBeteiligung {

    protected List<TypeGDSBeteiligung.Rolle> rolle;
    @XmlElement(required = true)
    protected TypeGDSBeteiligter beteiligter;

    /**
     * Gets the value of the rolle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the rolle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRolle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeGDSBeteiligung.Rolle }
     * 
     * 
     */
    public List<TypeGDSBeteiligung.Rolle> getRolle() {
        if (rolle == null) {
            rolle = new ArrayList<TypeGDSBeteiligung.Rolle>();
        }
        return this.rolle;
    }

    /**
     * Gets the value of the beteiligter property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSBeteiligter }
     *     
     */
    public TypeGDSBeteiligter getBeteiligter() {
        return beteiligter;
    }

    /**
     * Sets the value of the beteiligter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSBeteiligter }
     *     
     */
    public void setBeteiligter(TypeGDSBeteiligter value) {
        this.beteiligter = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="rollennummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="rollenID" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="id" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *                   &lt;element name="ref.instanznummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="rollenbezeichnung" type="{http://www.xjustiz.de}Code.GDS.Rollenbezeichnung" minOccurs="0"/&gt;
     *         &lt;element name="nr" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="geschaeftszeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *         &lt;element name="referenz" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="naehereBezeichnung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rollennummer",
        "rollenID",
        "rollenbezeichnung",
        "nr",
        "geschaeftszeichen",
        "referenz",
        "naehereBezeichnung"
    })
    public static class Rolle {

        protected String rollennummer;
        protected List<TypeGDSBeteiligung.Rolle.RollenID> rollenID;
        protected CodeGDSRollenbezeichnung rollenbezeichnung;
        @XmlElement(defaultValue = "1")
        protected BigInteger nr;
        protected String geschaeftszeichen;
        protected List<TypeGDSRefRollennummer> referenz;
        protected String naehereBezeichnung;

        /**
         * Gets the value of the rollennummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRollennummer() {
            return rollennummer;
        }

        /**
         * Sets the value of the rollennummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRollennummer(String value) {
            this.rollennummer = value;
        }

        /**
         * Gets the value of the rollenID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the rollenID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRollenID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeGDSBeteiligung.Rolle.RollenID }
         * 
         * 
         */
        public List<TypeGDSBeteiligung.Rolle.RollenID> getRollenID() {
            if (rollenID == null) {
                rollenID = new ArrayList<TypeGDSBeteiligung.Rolle.RollenID>();
            }
            return this.rollenID;
        }

        /**
         * Gets the value of the rollenbezeichnung property.
         * 
         * @return
         *     possible object is
         *     {@link CodeGDSRollenbezeichnung }
         *     
         */
        public CodeGDSRollenbezeichnung getRollenbezeichnung() {
            return rollenbezeichnung;
        }

        /**
         * Sets the value of the rollenbezeichnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeGDSRollenbezeichnung }
         *     
         */
        public void setRollenbezeichnung(CodeGDSRollenbezeichnung value) {
            this.rollenbezeichnung = value;
        }

        /**
         * Gets the value of the nr property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNr() {
            return nr;
        }

        /**
         * Sets the value of the nr property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNr(BigInteger value) {
            this.nr = value;
        }

        /**
         * Gets the value of the geschaeftszeichen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeschaeftszeichen() {
            return geschaeftszeichen;
        }

        /**
         * Sets the value of the geschaeftszeichen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeschaeftszeichen(String value) {
            this.geschaeftszeichen = value;
        }

        /**
         * Gets the value of the referenz property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the referenz property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReferenz().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeGDSRefRollennummer }
         * 
         * 
         */
        public List<TypeGDSRefRollennummer> getReferenz() {
            if (referenz == null) {
                referenz = new ArrayList<TypeGDSRefRollennummer>();
            }
            return this.referenz;
        }

        /**
         * Gets the value of the naehereBezeichnung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaehereBezeichnung() {
            return naehereBezeichnung;
        }

        /**
         * Sets the value of the naehereBezeichnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaehereBezeichnung(String value) {
            this.naehereBezeichnung = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="id" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
         *         &lt;element name="ref.instanznummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "refInstanznummer"
        })
        public static class RollenID {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(name = "ref.instanznummer", required = true)
            protected String refInstanznummer;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the refInstanznummer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefInstanznummer() {
                return refInstanznummer;
            }

            /**
             * Sets the value of the refInstanznummer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefInstanznummer(String value) {
                this.refInstanznummer = value;
            }

        }

    }

}
