//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:44:10 PM CEST 
//


package com.java.xsd.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.ENOVA.Erwerber_Veraeusserer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.ENOVA.Erwerber_Veraeusserer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="auswahl_erwerber_veraeusserer"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="erwerber" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                   &lt;element name="veraeusserer" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="anteilAmErwerb_Veraeusserung" type="{http://www.xjustiz.de}Type.DABAG.Anteil"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.ENOVA.Erwerber_Veraeusserer", propOrder = {
    "auswahlErwerberVeraeusserer",
    "anteilAmErwerbVeraeusserung"
})
public class TypeENOVAErwerberVeraeusserer {

    @XmlElement(name = "auswahl_erwerber_veraeusserer", required = true)
    protected TypeENOVAErwerberVeraeusserer.AuswahlErwerberVeraeusserer auswahlErwerberVeraeusserer;
    @XmlElement(name = "anteilAmErwerb_Veraeusserung", required = true)
    protected TypeDABAGAnteil anteilAmErwerbVeraeusserung;

    /**
     * Gets the value of the auswahlErwerberVeraeusserer property.
     * 
     * @return
     *     possible object is
     *     {@link TypeENOVAErwerberVeraeusserer.AuswahlErwerberVeraeusserer }
     *     
     */
    public TypeENOVAErwerberVeraeusserer.AuswahlErwerberVeraeusserer getAuswahlErwerberVeraeusserer() {
        return auswahlErwerberVeraeusserer;
    }

    /**
     * Sets the value of the auswahlErwerberVeraeusserer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeENOVAErwerberVeraeusserer.AuswahlErwerberVeraeusserer }
     *     
     */
    public void setAuswahlErwerberVeraeusserer(TypeENOVAErwerberVeraeusserer.AuswahlErwerberVeraeusserer value) {
        this.auswahlErwerberVeraeusserer = value;
    }

    /**
     * Gets the value of the anteilAmErwerbVeraeusserung property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDABAGAnteil }
     *     
     */
    public TypeDABAGAnteil getAnteilAmErwerbVeraeusserung() {
        return anteilAmErwerbVeraeusserung;
    }

    /**
     * Sets the value of the anteilAmErwerbVeraeusserung property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDABAGAnteil }
     *     
     */
    public void setAnteilAmErwerbVeraeusserung(TypeDABAGAnteil value) {
        this.anteilAmErwerbVeraeusserung = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="erwerber" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *         &lt;element name="veraeusserer" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "erwerber",
        "veraeusserer"
    })
    public static class AuswahlErwerberVeraeusserer {

        protected TypeGDSRefRollennummer erwerber;
        protected TypeGDSRefRollennummer veraeusserer;

        /**
         * Gets the value of the erwerber property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getErwerber() {
            return erwerber;
        }

        /**
         * Sets the value of the erwerber property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setErwerber(TypeGDSRefRollennummer value) {
            this.erwerber = value;
        }

        /**
         * Gets the value of the veraeusserer property.
         * 
         * @return
         *     possible object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public TypeGDSRefRollennummer getVeraeusserer() {
            return veraeusserer;
        }

        /**
         * Sets the value of the veraeusserer property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeGDSRefRollennummer }
         *     
         */
        public void setVeraeusserer(TypeGDSRefRollennummer value) {
            this.veraeusserer = value;
        }

    }

}
