//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:28 PM CEST 
//


package com.java.xsd.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vag.fehler.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="vag.fehler"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="FA00000"/&gt;
 *     &lt;enumeration value="FA00001"/&gt;
 *     &lt;enumeration value="FA00002"/&gt;
 *     &lt;enumeration value="FE00001"/&gt;
 *     &lt;enumeration value="FE00002"/&gt;
 *     &lt;enumeration value="FE00003"/&gt;
 *     &lt;enumeration value="FE00004"/&gt;
 *     &lt;enumeration value="FE00005"/&gt;
 *     &lt;enumeration value="FE00006"/&gt;
 *     &lt;enumeration value="FE00007"/&gt;
 *     &lt;enumeration value="FE00021"/&gt;
 *     &lt;enumeration value="FE00031"/&gt;
 *     &lt;enumeration value="FE00042"/&gt;
 *     &lt;enumeration value="FE00043"/&gt;
 *     &lt;enumeration value="FE00044"/&gt;
 *     &lt;enumeration value="FE00045"/&gt;
 *     &lt;enumeration value="FE00046"/&gt;
 *     &lt;enumeration value="FE00100"/&gt;
 *     &lt;enumeration value="FE00110"/&gt;
 *     &lt;enumeration value="FE00120"/&gt;
 *     &lt;enumeration value="FE01001"/&gt;
 *     &lt;enumeration value="FE01002"/&gt;
 *     &lt;enumeration value="FE01003"/&gt;
 *     &lt;enumeration value="FE01101"/&gt;
 *     &lt;enumeration value="FE02001"/&gt;
 *     &lt;enumeration value="FE02002"/&gt;
 *     &lt;enumeration value="FE02003"/&gt;
 *     &lt;enumeration value="FE09999"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "vag.fehler")
@XmlEnum
public enum VagFehler {

    @XmlEnumValue("FA00000")
    FA_00000("FA00000"),
    @XmlEnumValue("FA00001")
    FA_00001("FA00001"),
    @XmlEnumValue("FA00002")
    FA_00002("FA00002"),
    @XmlEnumValue("FE00001")
    FE_00001("FE00001"),
    @XmlEnumValue("FE00002")
    FE_00002("FE00002"),
    @XmlEnumValue("FE00003")
    FE_00003("FE00003"),
    @XmlEnumValue("FE00004")
    FE_00004("FE00004"),
    @XmlEnumValue("FE00005")
    FE_00005("FE00005"),
    @XmlEnumValue("FE00006")
    FE_00006("FE00006"),
    @XmlEnumValue("FE00007")
    FE_00007("FE00007"),
    @XmlEnumValue("FE00021")
    FE_00021("FE00021"),
    @XmlEnumValue("FE00031")
    FE_00031("FE00031"),
    @XmlEnumValue("FE00042")
    FE_00042("FE00042"),
    @XmlEnumValue("FE00043")
    FE_00043("FE00043"),
    @XmlEnumValue("FE00044")
    FE_00044("FE00044"),
    @XmlEnumValue("FE00045")
    FE_00045("FE00045"),
    @XmlEnumValue("FE00046")
    FE_00046("FE00046"),
    @XmlEnumValue("FE00100")
    FE_00100("FE00100"),
    @XmlEnumValue("FE00110")
    FE_00110("FE00110"),
    @XmlEnumValue("FE00120")
    FE_00120("FE00120"),
    @XmlEnumValue("FE01001")
    FE_01001("FE01001"),
    @XmlEnumValue("FE01002")
    FE_01002("FE01002"),
    @XmlEnumValue("FE01003")
    FE_01003("FE01003"),
    @XmlEnumValue("FE01101")
    FE_01101("FE01101"),
    @XmlEnumValue("FE02001")
    FE_02001("FE02001"),
    @XmlEnumValue("FE02002")
    FE_02002("FE02002"),
    @XmlEnumValue("FE02003")
    FE_02003("FE02003"),
    @XmlEnumValue("FE09999")
    FE_09999("FE09999");
    private final String value;

    VagFehler(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VagFehler fromValue(String v) {
        for (VagFehler c: VagFehler.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
