//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:43 PM CEST 
//


package com.java.xsd.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for zvr.antwortart.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="zvr.antwortart"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Download"/&gt;
 *     &lt;enumeration value="EGVP"/&gt;
 *     &lt;enumeration value="Fax"/&gt;
 *     &lt;enumeration value="Post"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "zvr.antwortart")
@XmlEnum
public enum ZvrAntwortart {

    @XmlEnumValue("Download")
    DOWNLOAD("Download"),
    EGVP("EGVP"),
    @XmlEnumValue("Fax")
    FAX("Fax"),
    @XmlEnumValue("Post")
    POST("Post");
    private final String value;

    ZvrAntwortart(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ZvrAntwortart fromValue(String v) {
        for (ZvrAntwortart c: ZvrAntwortart.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
