//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:41 PM CEST 
//


package com.java.xsd.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/&gt;
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/&gt;
 *         &lt;element name="fachdaten"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="uebermittlung.vermoegensverzeichnis" type="{http://www.xjustiz.de}Type.VSTR.Uebermittlung.Vermoegensverzeichnis"/&gt;
 *                   &lt;element name="beteiligter.zusatz" type="{http://www.xjustiz.de}Type.VSTR.Beteiligter.Zusatz"/&gt;
 *                   &lt;element name="ergebnisDerVerarbeitung"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ergebnis.code" type="{http://www.xjustiz.de}Code.VSTR.Verarbeitungsergebnis.Schuldnerverzeichnis"/&gt;
 *                             &lt;element name="ergebnis.ergaenzenderFehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.vstr.vermoegensverzeichnis.uebermittlungsbestaetigung.portal.0900007")
public class NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten }
     *     
     */
    public NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="uebermittlung.vermoegensverzeichnis" type="{http://www.xjustiz.de}Type.VSTR.Uebermittlung.Vermoegensverzeichnis"/&gt;
     *         &lt;element name="beteiligter.zusatz" type="{http://www.xjustiz.de}Type.VSTR.Beteiligter.Zusatz"/&gt;
     *         &lt;element name="ergebnisDerVerarbeitung"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ergebnis.code" type="{http://www.xjustiz.de}Code.VSTR.Verarbeitungsergebnis.Schuldnerverzeichnis"/&gt;
     *                   &lt;element name="ergebnis.ergaenzenderFehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uebermittlungVermoegensverzeichnis",
        "beteiligterZusatz",
        "ergebnisDerVerarbeitung"
    })
    public static class Fachdaten {

        @XmlElement(name = "uebermittlung.vermoegensverzeichnis", required = true)
        protected TypeVSTRUebermittlungVermoegensverzeichnis uebermittlungVermoegensverzeichnis;
        @XmlElement(name = "beteiligter.zusatz", required = true)
        protected TypeVSTRBeteiligterZusatz beteiligterZusatz;
        @XmlElement(required = true)
        protected NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten.ErgebnisDerVerarbeitung ergebnisDerVerarbeitung;

        /**
         * Gets the value of the uebermittlungVermoegensverzeichnis property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVSTRUebermittlungVermoegensverzeichnis }
         *     
         */
        public TypeVSTRUebermittlungVermoegensverzeichnis getUebermittlungVermoegensverzeichnis() {
            return uebermittlungVermoegensverzeichnis;
        }

        /**
         * Sets the value of the uebermittlungVermoegensverzeichnis property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVSTRUebermittlungVermoegensverzeichnis }
         *     
         */
        public void setUebermittlungVermoegensverzeichnis(TypeVSTRUebermittlungVermoegensverzeichnis value) {
            this.uebermittlungVermoegensverzeichnis = value;
        }

        /**
         * Gets the value of the beteiligterZusatz property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVSTRBeteiligterZusatz }
         *     
         */
        public TypeVSTRBeteiligterZusatz getBeteiligterZusatz() {
            return beteiligterZusatz;
        }

        /**
         * Sets the value of the beteiligterZusatz property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVSTRBeteiligterZusatz }
         *     
         */
        public void setBeteiligterZusatz(TypeVSTRBeteiligterZusatz value) {
            this.beteiligterZusatz = value;
        }

        /**
         * Gets the value of the ergebnisDerVerarbeitung property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten.ErgebnisDerVerarbeitung }
         *     
         */
        public NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten.ErgebnisDerVerarbeitung getErgebnisDerVerarbeitung() {
            return ergebnisDerVerarbeitung;
        }

        /**
         * Sets the value of the ergebnisDerVerarbeitung property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten.ErgebnisDerVerarbeitung }
         *     
         */
        public void setErgebnisDerVerarbeitung(NachrichtVstrVermoegensverzeichnisUebermittlungsbestaetigungPortal0900007 .Fachdaten.ErgebnisDerVerarbeitung value) {
            this.ergebnisDerVerarbeitung = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ergebnis.code" type="{http://www.xjustiz.de}Code.VSTR.Verarbeitungsergebnis.Schuldnerverzeichnis"/&gt;
         *         &lt;element name="ergebnis.ergaenzenderFehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ergebnisCode",
            "ergebnisErgaenzenderFehlertext"
        })
        public static class ErgebnisDerVerarbeitung {

            @XmlElement(name = "ergebnis.code", required = true)
            protected CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis ergebnisCode;
            @XmlElement(name = "ergebnis.ergaenzenderFehlertext")
            protected String ergebnisErgaenzenderFehlertext;

            /**
             * Gets the value of the ergebnisCode property.
             * 
             * @return
             *     possible object is
             *     {@link CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis }
             *     
             */
            public CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis getErgebnisCode() {
                return ergebnisCode;
            }

            /**
             * Sets the value of the ergebnisCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis }
             *     
             */
            public void setErgebnisCode(CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis value) {
                this.ergebnisCode = value;
            }

            /**
             * Gets the value of the ergebnisErgaenzenderFehlertext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getErgebnisErgaenzenderFehlertext() {
                return ergebnisErgaenzenderFehlertext;
            }

            /**
             * Sets the value of the ergebnisErgaenzenderFehlertext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setErgebnisErgaenzenderFehlertext(String value) {
                this.ergebnisErgaenzenderFehlertext = value;
            }

        }

    }

}
