//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:35 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/&gt;
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/&gt;
 *         &lt;element name="fachdaten"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="uebermittelndeStelle" type="{http://www.xjustiz.de}Type.STRAF.BFJ.UebermittelndeStelle"/&gt;
 *                   &lt;element name="steuerungsdaten"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="auswahl_nachrichtencode"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice&gt;
 *                                       &lt;element name="nachrichtencode.nachricht_100" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Anfrage.UnbeschraenkteAuskunft.Typ3"/&gt;
 *                                       &lt;element name="nachrichtencode.nachricht_101" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Antrag.Behoerdenfuehrungszeugnis.Typ3"/&gt;
 *                                     &lt;/choice&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="verwendungszweck" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Verwendungszweck"/&gt;
 *                             &lt;element name="zusaetzlAnfrageTCN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="keineAnfrageTCN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="auslandsanfrage" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="anfrageland" type="{http://www.xjustiz.de}Code.GDS.Staaten.Typ3" maxOccurs="4"/&gt;
 *                                       &lt;element name="zustimmung.betroffenePerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="grund.behoerdenfuehrungszeugnis" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Behoerdenfuehrungszeugnis.BZR.Grund.Typ3" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="weitereAngabenBeteiligter" type="{http://www.xjustiz.de}Type.STRAF.BFJ.WeitereAngabenBeteiligter" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.straf.bfj.bzr.auskunftserteilung.anfrage.0500100")
public class NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten }
     *     
     */
    public NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="uebermittelndeStelle" type="{http://www.xjustiz.de}Type.STRAF.BFJ.UebermittelndeStelle"/&gt;
     *         &lt;element name="steuerungsdaten"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="auswahl_nachrichtencode"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;choice&gt;
     *                             &lt;element name="nachrichtencode.nachricht_100" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Anfrage.UnbeschraenkteAuskunft.Typ3"/&gt;
     *                             &lt;element name="nachrichtencode.nachricht_101" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Antrag.Behoerdenfuehrungszeugnis.Typ3"/&gt;
     *                           &lt;/choice&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="verwendungszweck" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Verwendungszweck"/&gt;
     *                   &lt;element name="zusaetzlAnfrageTCN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="keineAnfrageTCN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="auslandsanfrage" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="anfrageland" type="{http://www.xjustiz.de}Code.GDS.Staaten.Typ3" maxOccurs="4"/&gt;
     *                             &lt;element name="zustimmung.betroffenePerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="grund.behoerdenfuehrungszeugnis" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Behoerdenfuehrungszeugnis.BZR.Grund.Typ3" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="weitereAngabenBeteiligter" type="{http://www.xjustiz.de}Type.STRAF.BFJ.WeitereAngabenBeteiligter" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uebermittelndeStelle",
        "steuerungsdaten",
        "weitereAngabenBeteiligter"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected TypeSTRAFBFJUebermittelndeStelle uebermittelndeStelle;
        @XmlElement(required = true)
        protected NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten steuerungsdaten;
        protected TypeSTRAFBFJWeitereAngabenBeteiligter weitereAngabenBeteiligter;

        /**
         * Gets the value of the uebermittelndeStelle property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSTRAFBFJUebermittelndeStelle }
         *     
         */
        public TypeSTRAFBFJUebermittelndeStelle getUebermittelndeStelle() {
            return uebermittelndeStelle;
        }

        /**
         * Sets the value of the uebermittelndeStelle property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSTRAFBFJUebermittelndeStelle }
         *     
         */
        public void setUebermittelndeStelle(TypeSTRAFBFJUebermittelndeStelle value) {
            this.uebermittelndeStelle = value;
        }

        /**
         * Gets the value of the steuerungsdaten property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten }
         *     
         */
        public NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten getSteuerungsdaten() {
            return steuerungsdaten;
        }

        /**
         * Sets the value of the steuerungsdaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten }
         *     
         */
        public void setSteuerungsdaten(NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten value) {
            this.steuerungsdaten = value;
        }

        /**
         * Gets the value of the weitereAngabenBeteiligter property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSTRAFBFJWeitereAngabenBeteiligter }
         *     
         */
        public TypeSTRAFBFJWeitereAngabenBeteiligter getWeitereAngabenBeteiligter() {
            return weitereAngabenBeteiligter;
        }

        /**
         * Sets the value of the weitereAngabenBeteiligter property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSTRAFBFJWeitereAngabenBeteiligter }
         *     
         */
        public void setWeitereAngabenBeteiligter(TypeSTRAFBFJWeitereAngabenBeteiligter value) {
            this.weitereAngabenBeteiligter = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="auswahl_nachrichtencode"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;choice&gt;
         *                   &lt;element name="nachrichtencode.nachricht_100" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Anfrage.UnbeschraenkteAuskunft.Typ3"/&gt;
         *                   &lt;element name="nachrichtencode.nachricht_101" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Antrag.Behoerdenfuehrungszeugnis.Typ3"/&gt;
         *                 &lt;/choice&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="verwendungszweck" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Verwendungszweck"/&gt;
         *         &lt;element name="zusaetzlAnfrageTCN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="keineAnfrageTCN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="auslandsanfrage" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="anfrageland" type="{http://www.xjustiz.de}Code.GDS.Staaten.Typ3" maxOccurs="4"/&gt;
         *                   &lt;element name="zustimmung.betroffenePerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="grund.behoerdenfuehrungszeugnis" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Behoerdenfuehrungszeugnis.BZR.Grund.Typ3" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "auswahlNachrichtencode",
            "verwendungszweck",
            "zusaetzlAnfrageTCN",
            "keineAnfrageTCN",
            "auslandsanfrage",
            "grundBehoerdenfuehrungszeugnis"
        })
        public static class Steuerungsdaten {

            @XmlElement(name = "auswahl_nachrichtencode", required = true)
            protected NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.AuswahlNachrichtencode auswahlNachrichtencode;
            @XmlElement(required = true)
            protected TypeSTRAFBFJVerwendungszweck verwendungszweck;
            protected Boolean zusaetzlAnfrageTCN;
            protected Boolean keineAnfrageTCN;
            protected NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.Auslandsanfrage auslandsanfrage;
            @XmlElement(name = "grund.behoerdenfuehrungszeugnis")
            protected CodeSTRAFBFJBehoerdenfuehrungszeugnisBZRGrundTyp3 grundBehoerdenfuehrungszeugnis;

            /**
             * Gets the value of the auswahlNachrichtencode property.
             * 
             * @return
             *     possible object is
             *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.AuswahlNachrichtencode }
             *     
             */
            public NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.AuswahlNachrichtencode getAuswahlNachrichtencode() {
                return auswahlNachrichtencode;
            }

            /**
             * Sets the value of the auswahlNachrichtencode property.
             * 
             * @param value
             *     allowed object is
             *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.AuswahlNachrichtencode }
             *     
             */
            public void setAuswahlNachrichtencode(NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.AuswahlNachrichtencode value) {
                this.auswahlNachrichtencode = value;
            }

            /**
             * Gets the value of the verwendungszweck property.
             * 
             * @return
             *     possible object is
             *     {@link TypeSTRAFBFJVerwendungszweck }
             *     
             */
            public TypeSTRAFBFJVerwendungszweck getVerwendungszweck() {
                return verwendungszweck;
            }

            /**
             * Sets the value of the verwendungszweck property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeSTRAFBFJVerwendungszweck }
             *     
             */
            public void setVerwendungszweck(TypeSTRAFBFJVerwendungszweck value) {
                this.verwendungszweck = value;
            }

            /**
             * Gets the value of the zusaetzlAnfrageTCN property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isZusaetzlAnfrageTCN() {
                return zusaetzlAnfrageTCN;
            }

            /**
             * Sets the value of the zusaetzlAnfrageTCN property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setZusaetzlAnfrageTCN(Boolean value) {
                this.zusaetzlAnfrageTCN = value;
            }

            /**
             * Gets the value of the keineAnfrageTCN property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isKeineAnfrageTCN() {
                return keineAnfrageTCN;
            }

            /**
             * Sets the value of the keineAnfrageTCN property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setKeineAnfrageTCN(Boolean value) {
                this.keineAnfrageTCN = value;
            }

            /**
             * Gets the value of the auslandsanfrage property.
             * 
             * @return
             *     possible object is
             *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.Auslandsanfrage }
             *     
             */
            public NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.Auslandsanfrage getAuslandsanfrage() {
                return auslandsanfrage;
            }

            /**
             * Sets the value of the auslandsanfrage property.
             * 
             * @param value
             *     allowed object is
             *     {@link NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.Auslandsanfrage }
             *     
             */
            public void setAuslandsanfrage(NachrichtStrafBfjBzrAuskunftserteilungAnfrage0500100 .Fachdaten.Steuerungsdaten.Auslandsanfrage value) {
                this.auslandsanfrage = value;
            }

            /**
             * Gets the value of the grundBehoerdenfuehrungszeugnis property.
             * 
             * @return
             *     possible object is
             *     {@link CodeSTRAFBFJBehoerdenfuehrungszeugnisBZRGrundTyp3 }
             *     
             */
            public CodeSTRAFBFJBehoerdenfuehrungszeugnisBZRGrundTyp3 getGrundBehoerdenfuehrungszeugnis() {
                return grundBehoerdenfuehrungszeugnis;
            }

            /**
             * Sets the value of the grundBehoerdenfuehrungszeugnis property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeSTRAFBFJBehoerdenfuehrungszeugnisBZRGrundTyp3 }
             *     
             */
            public void setGrundBehoerdenfuehrungszeugnis(CodeSTRAFBFJBehoerdenfuehrungszeugnisBZRGrundTyp3 value) {
                this.grundBehoerdenfuehrungszeugnis = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="anfrageland" type="{http://www.xjustiz.de}Code.GDS.Staaten.Typ3" maxOccurs="4"/&gt;
             *         &lt;element name="zustimmung.betroffenePerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "anfrageland",
                "zustimmungBetroffenePerson"
            })
            public static class Auslandsanfrage {

                @XmlElement(required = true)
                protected List<CodeGDSStaatenTyp3> anfrageland;
                @XmlElement(name = "zustimmung.betroffenePerson")
                protected boolean zustimmungBetroffenePerson;

                /**
                 * Gets the value of the anfrageland property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the anfrageland property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAnfrageland().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CodeGDSStaatenTyp3 }
                 * 
                 * 
                 */
                public List<CodeGDSStaatenTyp3> getAnfrageland() {
                    if (anfrageland == null) {
                        anfrageland = new ArrayList<CodeGDSStaatenTyp3>();
                    }
                    return this.anfrageland;
                }

                /**
                 * Gets the value of the zustimmungBetroffenePerson property.
                 * 
                 */
                public boolean isZustimmungBetroffenePerson() {
                    return zustimmungBetroffenePerson;
                }

                /**
                 * Sets the value of the zustimmungBetroffenePerson property.
                 * 
                 */
                public void setZustimmungBetroffenePerson(boolean value) {
                    this.zustimmungBetroffenePerson = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="nachrichtencode.nachricht_100" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Anfrage.UnbeschraenkteAuskunft.Typ3"/&gt;
             *         &lt;element name="nachrichtencode.nachricht_101" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.BZR.Antrag.Behoerdenfuehrungszeugnis.Typ3"/&gt;
             *       &lt;/choice&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nachrichtencodeNachricht100",
                "nachrichtencodeNachricht101"
            })
            public static class AuswahlNachrichtencode {

                @XmlElement(name = "nachrichtencode.nachricht_100")
                protected CodeSTRAFBFJNachrichtencodeBZRAnfrageUnbeschraenkteAuskunftTyp3 nachrichtencodeNachricht100;
                @XmlElement(name = "nachrichtencode.nachricht_101")
                protected CodeSTRAFBFJNachrichtencodeBZRAntragBehoerdenfuehrungszeugnisTyp3 nachrichtencodeNachricht101;

                /**
                 * Gets the value of the nachrichtencodeNachricht100 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CodeSTRAFBFJNachrichtencodeBZRAnfrageUnbeschraenkteAuskunftTyp3 }
                 *     
                 */
                public CodeSTRAFBFJNachrichtencodeBZRAnfrageUnbeschraenkteAuskunftTyp3 getNachrichtencodeNachricht100() {
                    return nachrichtencodeNachricht100;
                }

                /**
                 * Sets the value of the nachrichtencodeNachricht100 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CodeSTRAFBFJNachrichtencodeBZRAnfrageUnbeschraenkteAuskunftTyp3 }
                 *     
                 */
                public void setNachrichtencodeNachricht100(CodeSTRAFBFJNachrichtencodeBZRAnfrageUnbeschraenkteAuskunftTyp3 value) {
                    this.nachrichtencodeNachricht100 = value;
                }

                /**
                 * Gets the value of the nachrichtencodeNachricht101 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CodeSTRAFBFJNachrichtencodeBZRAntragBehoerdenfuehrungszeugnisTyp3 }
                 *     
                 */
                public CodeSTRAFBFJNachrichtencodeBZRAntragBehoerdenfuehrungszeugnisTyp3 getNachrichtencodeNachricht101() {
                    return nachrichtencodeNachricht101;
                }

                /**
                 * Sets the value of the nachrichtencodeNachricht101 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CodeSTRAFBFJNachrichtencodeBZRAntragBehoerdenfuehrungszeugnisTyp3 }
                 *     
                 */
                public void setNachrichtencodeNachricht101(CodeSTRAFBFJNachrichtencodeBZRAntragBehoerdenfuehrungszeugnisTyp3 value) {
                    this.nachrichtencodeNachricht101 = value;
                }

            }

        }

    }

}
