//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:35 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.xjustiz.de}Type.GDS.Basisnachricht"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte" minOccurs="0"/&gt;
 *         &lt;element name="fachdaten"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="bussgeldbescheid" type="{http://www.xjustiz.de}Type.STRAF.OWI.Bussgeldbescheid" minOccurs="0"/&gt;
 *                   &lt;element name="datumDesEinspruchs" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="nachtraeglicheMitteilungen.bussgeldbescheid" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="mitteilung.zahlung" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="teilzahlung.einzeln" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *                                                 &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="teilzahlung.auslagen" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *                                                 &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="mitteilung.stornierung" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="stornierung.einzeln" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *                                                 &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="stornierung.auslagen" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                                                 &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="ruecknahme" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="ruecknahme.EHaftAntrag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schriftgutobjekte",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.straf.owi.verfahrensmitteilung.externAnJustiz.0500010")
public class NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010
    extends TypeGDSBasisnachricht
{

    protected TypeGDSSchriftgutobjekte schriftgutobjekte;
    @XmlElement(required = true)
    protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten fachdaten;

    /**
     * Gets the value of the schriftgutobjekte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public TypeGDSSchriftgutobjekte getSchriftgutobjekte() {
        return schriftgutobjekte;
    }

    /**
     * Sets the value of the schriftgutobjekte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public void setSchriftgutobjekte(TypeGDSSchriftgutobjekte value) {
        this.schriftgutobjekte = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten }
     *     
     */
    public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="bussgeldbescheid" type="{http://www.xjustiz.de}Type.STRAF.OWI.Bussgeldbescheid" minOccurs="0"/&gt;
     *         &lt;element name="datumDesEinspruchs" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="nachtraeglicheMitteilungen.bussgeldbescheid" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="mitteilung.zahlung" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="teilzahlung.einzeln" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
     *                                       &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="teilzahlung.auslagen" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
     *                                       &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="mitteilung.stornierung" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="stornierung.einzeln" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
     *                                       &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="stornierung.auslagen" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                                       &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="ruecknahme" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="ruecknahme.EHaftAntrag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bussgeldbescheid",
        "datumDesEinspruchs",
        "nachtraeglicheMitteilungenBussgeldbescheid"
    })
    public static class Fachdaten {

        protected TypeSTRAFOWIBussgeldbescheid bussgeldbescheid;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumDesEinspruchs;
        @XmlElement(name = "nachtraeglicheMitteilungen.bussgeldbescheid")
        protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid nachtraeglicheMitteilungenBussgeldbescheid;

        /**
         * Gets the value of the bussgeldbescheid property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSTRAFOWIBussgeldbescheid }
         *     
         */
        public TypeSTRAFOWIBussgeldbescheid getBussgeldbescheid() {
            return bussgeldbescheid;
        }

        /**
         * Sets the value of the bussgeldbescheid property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSTRAFOWIBussgeldbescheid }
         *     
         */
        public void setBussgeldbescheid(TypeSTRAFOWIBussgeldbescheid value) {
            this.bussgeldbescheid = value;
        }

        /**
         * Gets the value of the datumDesEinspruchs property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumDesEinspruchs() {
            return datumDesEinspruchs;
        }

        /**
         * Sets the value of the datumDesEinspruchs property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumDesEinspruchs(XMLGregorianCalendar value) {
            this.datumDesEinspruchs = value;
        }

        /**
         * Gets the value of the nachtraeglicheMitteilungenBussgeldbescheid property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid }
         *     
         */
        public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid getNachtraeglicheMitteilungenBussgeldbescheid() {
            return nachtraeglicheMitteilungenBussgeldbescheid;
        }

        /**
         * Sets the value of the nachtraeglicheMitteilungenBussgeldbescheid property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid }
         *     
         */
        public void setNachtraeglicheMitteilungenBussgeldbescheid(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid value) {
            this.nachtraeglicheMitteilungenBussgeldbescheid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="mitteilung.zahlung" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="teilzahlung.einzeln" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
         *                             &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="teilzahlung.auslagen" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
         *                             &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="mitteilung.stornierung" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="stornierung.einzeln" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
         *                             &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="stornierung.auslagen" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *                             &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="ruecknahme" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="ruecknahme.EHaftAntrag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mitteilungZahlung",
            "mitteilungStornierung",
            "ruecknahme"
        })
        public static class NachtraeglicheMitteilungenBussgeldbescheid {

            @XmlElement(name = "mitteilung.zahlung")
            protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung mitteilungZahlung;
            @XmlElement(name = "mitteilung.stornierung")
            protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung mitteilungStornierung;
            protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.Ruecknahme ruecknahme;

            /**
             * Gets the value of the mitteilungZahlung property.
             * 
             * @return
             *     possible object is
             *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung }
             *     
             */
            public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung getMitteilungZahlung() {
                return mitteilungZahlung;
            }

            /**
             * Sets the value of the mitteilungZahlung property.
             * 
             * @param value
             *     allowed object is
             *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung }
             *     
             */
            public void setMitteilungZahlung(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung value) {
                this.mitteilungZahlung = value;
            }

            /**
             * Gets the value of the mitteilungStornierung property.
             * 
             * @return
             *     possible object is
             *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung }
             *     
             */
            public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung getMitteilungStornierung() {
                return mitteilungStornierung;
            }

            /**
             * Sets the value of the mitteilungStornierung property.
             * 
             * @param value
             *     allowed object is
             *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung }
             *     
             */
            public void setMitteilungStornierung(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung value) {
                this.mitteilungStornierung = value;
            }

            /**
             * Gets the value of the ruecknahme property.
             * 
             * @return
             *     possible object is
             *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.Ruecknahme }
             *     
             */
            public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.Ruecknahme getRuecknahme() {
                return ruecknahme;
            }

            /**
             * Sets the value of the ruecknahme property.
             * 
             * @param value
             *     allowed object is
             *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.Ruecknahme }
             *     
             */
            public void setRuecknahme(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.Ruecknahme value) {
                this.ruecknahme = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="stornierung.einzeln" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
             *                   &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="stornierung.auslagen" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
             *                   &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "stornierungEinzeln",
                "stornierungAuslagen"
            })
            public static class MitteilungStornierung {

                @XmlElement(name = "stornierung.einzeln")
                protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungEinzeln stornierungEinzeln;
                @XmlElement(name = "stornierung.auslagen")
                protected NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungAuslagen stornierungAuslagen;

                /**
                 * Gets the value of the stornierungEinzeln property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungEinzeln }
                 *     
                 */
                public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungEinzeln getStornierungEinzeln() {
                    return stornierungEinzeln;
                }

                /**
                 * Sets the value of the stornierungEinzeln property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungEinzeln }
                 *     
                 */
                public void setStornierungEinzeln(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungEinzeln value) {
                    this.stornierungEinzeln = value;
                }

                /**
                 * Gets the value of the stornierungAuslagen property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungAuslagen }
                 *     
                 */
                public NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungAuslagen getStornierungAuslagen() {
                    return stornierungAuslagen;
                }

                /**
                 * Sets the value of the stornierungAuslagen property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungAuslagen }
                 *     
                 */
                public void setStornierungAuslagen(NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungStornierung.StornierungAuslagen value) {
                    this.stornierungAuslagen = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
                 *         &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "teilzahlungAuslagenEinzeln",
                    "teilzahlungAuslagenDatum"
                })
                public static class StornierungAuslagen {

                    @XmlElement(name = "teilzahlung.auslagen.einzeln")
                    protected double teilzahlungAuslagenEinzeln;
                    @XmlElement(name = "teilzahlung.auslagen.datum")
                    protected String teilzahlungAuslagenDatum;

                    /**
                     * Gets the value of the teilzahlungAuslagenEinzeln property.
                     * 
                     */
                    public double getTeilzahlungAuslagenEinzeln() {
                        return teilzahlungAuslagenEinzeln;
                    }

                    /**
                     * Sets the value of the teilzahlungAuslagenEinzeln property.
                     * 
                     */
                    public void setTeilzahlungAuslagenEinzeln(double value) {
                        this.teilzahlungAuslagenEinzeln = value;
                    }

                    /**
                     * Gets the value of the teilzahlungAuslagenDatum property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTeilzahlungAuslagenDatum() {
                        return teilzahlungAuslagenDatum;
                    }

                    /**
                     * Sets the value of the teilzahlungAuslagenDatum property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTeilzahlungAuslagenDatum(String value) {
                        this.teilzahlungAuslagenDatum = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
                 *         &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "teilzahlungEinzeln",
                    "teilzahlungDatum"
                })
                public static class StornierungEinzeln {

                    @XmlElement(name = "teilzahlung.einzeln")
                    protected Double teilzahlungEinzeln;
                    @XmlElement(name = "teilzahlung.datum")
                    protected String teilzahlungDatum;

                    /**
                     * Gets the value of the teilzahlungEinzeln property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getTeilzahlungEinzeln() {
                        return teilzahlungEinzeln;
                    }

                    /**
                     * Sets the value of the teilzahlungEinzeln property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setTeilzahlungEinzeln(Double value) {
                        this.teilzahlungEinzeln = value;
                    }

                    /**
                     * Gets the value of the teilzahlungDatum property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTeilzahlungDatum() {
                        return teilzahlungDatum;
                    }

                    /**
                     * Sets the value of the teilzahlungDatum property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTeilzahlungDatum(String value) {
                        this.teilzahlungDatum = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="teilzahlung.einzeln" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
             *                   &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="teilzahlung.auslagen" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
             *                   &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "teilzahlungEinzeln",
                "teilzahlungAuslagen"
            })
            public static class MitteilungZahlung {

                @XmlElement(name = "teilzahlung.einzeln")
                protected List<NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungEinzeln> teilzahlungEinzeln;
                @XmlElement(name = "teilzahlung.auslagen")
                protected List<NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungAuslagen> teilzahlungAuslagen;

                /**
                 * Gets the value of the teilzahlungEinzeln property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the teilzahlungEinzeln property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTeilzahlungEinzeln().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungEinzeln }
                 * 
                 * 
                 */
                public List<NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungEinzeln> getTeilzahlungEinzeln() {
                    if (teilzahlungEinzeln == null) {
                        teilzahlungEinzeln = new ArrayList<NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungEinzeln>();
                    }
                    return this.teilzahlungEinzeln;
                }

                /**
                 * Gets the value of the teilzahlungAuslagen property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the teilzahlungAuslagen property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTeilzahlungAuslagen().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungAuslagen }
                 * 
                 * 
                 */
                public List<NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungAuslagen> getTeilzahlungAuslagen() {
                    if (teilzahlungAuslagen == null) {
                        teilzahlungAuslagen = new ArrayList<NachrichtStrafOwiVerfahrensmitteilungExternAnJustiz0500010 .Fachdaten.NachtraeglicheMitteilungenBussgeldbescheid.MitteilungZahlung.TeilzahlungAuslagen>();
                    }
                    return this.teilzahlungAuslagen;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="teilzahlung.auslagen.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
                 *         &lt;element name="teilzahlung.auslagen.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "teilzahlungAuslagenEinzeln",
                    "teilzahlungAuslagenDatum"
                })
                public static class TeilzahlungAuslagen {

                    @XmlElement(name = "teilzahlung.auslagen.einzeln")
                    protected Double teilzahlungAuslagenEinzeln;
                    @XmlElement(name = "teilzahlung.auslagen.datum")
                    protected String teilzahlungAuslagenDatum;

                    /**
                     * Gets the value of the teilzahlungAuslagenEinzeln property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getTeilzahlungAuslagenEinzeln() {
                        return teilzahlungAuslagenEinzeln;
                    }

                    /**
                     * Sets the value of the teilzahlungAuslagenEinzeln property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setTeilzahlungAuslagenEinzeln(Double value) {
                        this.teilzahlungAuslagenEinzeln = value;
                    }

                    /**
                     * Gets the value of the teilzahlungAuslagenDatum property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTeilzahlungAuslagenDatum() {
                        return teilzahlungAuslagenDatum;
                    }

                    /**
                     * Sets the value of the teilzahlungAuslagenDatum property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTeilzahlungAuslagenDatum(String value) {
                        this.teilzahlungAuslagenDatum = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="teilzahlung.einzeln" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
                 *         &lt;element name="teilzahlung.datum" type="{http://www.xjustiz.de}Type.GDS.Datumsangabe" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "teilzahlungEinzeln",
                    "teilzahlungDatum"
                })
                public static class TeilzahlungEinzeln {

                    @XmlElement(name = "teilzahlung.einzeln")
                    protected Double teilzahlungEinzeln;
                    @XmlElement(name = "teilzahlung.datum")
                    protected String teilzahlungDatum;

                    /**
                     * Gets the value of the teilzahlungEinzeln property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getTeilzahlungEinzeln() {
                        return teilzahlungEinzeln;
                    }

                    /**
                     * Sets the value of the teilzahlungEinzeln property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setTeilzahlungEinzeln(Double value) {
                        this.teilzahlungEinzeln = value;
                    }

                    /**
                     * Gets the value of the teilzahlungDatum property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTeilzahlungDatum() {
                        return teilzahlungDatum;
                    }

                    /**
                     * Sets the value of the teilzahlungDatum property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTeilzahlungDatum(String value) {
                        this.teilzahlungDatum = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="ruecknahme.EHaftAntrag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ruecknahmeEHaftAntrag"
            })
            public static class Ruecknahme {

                @XmlElement(name = "ruecknahme.EHaftAntrag")
                protected boolean ruecknahmeEHaftAntrag;

                /**
                 * Gets the value of the ruecknahmeEHaftAntrag property.
                 * 
                 */
                public boolean isRuecknahmeEHaftAntrag() {
                    return ruecknahmeEHaftAntrag;
                }

                /**
                 * Sets the value of the ruecknahmeEHaftAntrag property.
                 * 
                 */
                public void setRuecknahmeEHaftAntrag(boolean value) {
                    this.ruecknahmeEHaftAntrag = value;
                }

            }

        }

    }

}
