//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:44:10 PM CEST 
//


package com.java.xsd.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.DABAG.Abtretung.Berechtigter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Abtretung.Berechtigter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="grund" type="{http://www.xjustiz.de}Code.DABAG.Abtretungsgrund" minOccurs="0"/&gt;
 *         &lt;element name="gegenstand" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *         &lt;element name="zusatz" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Abtretung.Berechtigter", propOrder = {
    "grund",
    "gegenstand",
    "zusatz"
})
public class TypeDABAGAbtretungBerechtigter {

    protected CodeDABAGAbtretungsgrund grund;
    protected String gegenstand;
    protected String zusatz;

    /**
     * Gets the value of the grund property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDABAGAbtretungsgrund }
     *     
     */
    public CodeDABAGAbtretungsgrund getGrund() {
        return grund;
    }

    /**
     * Sets the value of the grund property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDABAGAbtretungsgrund }
     *     
     */
    public void setGrund(CodeDABAGAbtretungsgrund value) {
        this.grund = value;
    }

    /**
     * Gets the value of the gegenstand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGegenstand() {
        return gegenstand;
    }

    /**
     * Sets the value of the gegenstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGegenstand(String value) {
        this.gegenstand = value;
    }

    /**
     * Gets the value of the zusatz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZusatz() {
        return zusatz;
    }

    /**
     * Sets the value of the zusatz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZusatz(String value) {
        this.zusatz = value;
    }

}
