//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.22 at 07:43:45 PM CEST 
//


package com.java.xsd.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Die Aufbewahrungsdauer legt fest, wie viele Jahre eine Akte oder ein Vorgang nach der Verfügung zur Akte (zdA-Verfügung) innerhalb der aktenführenden Stelle aufzubewahren ist oder ob die Aufbewahrung unbefristet erfolgen soll.
 * 
 * <p>Java class for Type.AUSS.Aufbewahrungsdauer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.AUSS.Aufbewahrungsdauer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="auswahl_aufbewahrungsdauer"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="anzahlJahre" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
 *                   &lt;element name="unbefristed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.AUSS.Aufbewahrungsdauer", propOrder = {
    "auswahlAufbewahrungsdauer"
})
public class TypeAUSSAufbewahrungsdauer {

    @XmlElement(name = "auswahl_aufbewahrungsdauer", required = true)
    protected TypeAUSSAufbewahrungsdauer.AuswahlAufbewahrungsdauer auswahlAufbewahrungsdauer;

    /**
     * Gets the value of the auswahlAufbewahrungsdauer property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAUSSAufbewahrungsdauer.AuswahlAufbewahrungsdauer }
     *     
     */
    public TypeAUSSAufbewahrungsdauer.AuswahlAufbewahrungsdauer getAuswahlAufbewahrungsdauer() {
        return auswahlAufbewahrungsdauer;
    }

    /**
     * Sets the value of the auswahlAufbewahrungsdauer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAUSSAufbewahrungsdauer.AuswahlAufbewahrungsdauer }
     *     
     */
    public void setAuswahlAufbewahrungsdauer(TypeAUSSAufbewahrungsdauer.AuswahlAufbewahrungsdauer value) {
        this.auswahlAufbewahrungsdauer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="anzahlJahre" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
     *         &lt;element name="unbefristed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "anzahlJahre",
        "unbefristed"
    })
    public static class AuswahlAufbewahrungsdauer {

        @XmlSchemaType(name = "unsignedShort")
        protected Integer anzahlJahre;
        protected Boolean unbefristed;

        /**
         * Gets the value of the anzahlJahre property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAnzahlJahre() {
            return anzahlJahre;
        }

        /**
         * Sets the value of the anzahlJahre property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAnzahlJahre(Integer value) {
            this.anzahlJahre = value;
        }

        /**
         * Gets the value of the unbefristed property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUnbefristed() {
            return unbefristed;
        }

        /**
         * Sets the value of the unbefristed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUnbefristed(Boolean value) {
            this.unbefristed = value;
        }

    }

}
